// DO NOT EDIT THIS FILE!
// This is the vitest.config.ts file provided by the core-gen4 stack. Do not edit this; instead, place any custom configuration settings
// in the `vitest.config.project.ts` file. If this file is modified, you are on your own and results of using the stack's vitest config
// cannot be supported.

import stackTestConfig from "@okta/ui-stacks-component-libraries-odyssey-contributions/dist/configs/vitest.config.js";
import { defineConfig, mergeConfig } from "vite";
import { type UserConfigFnPromise } from "vitest/config";

import viteConfig from "./vite.config.js";
import projectTestConfig from "./vitest.config.project.js";

// Merge, in this order:
// - the project's vite.config.js
// - the stack's vitest.config.js
// - the project's vitest.config.project.js
export default defineConfig(async (env) =>
  mergeConfig(
    mergeConfig(
      typeof viteConfig === "function" ? await viteConfig(env) : viteConfig,
      stackTestConfig,
    ),
    typeof projectTestConfig === "function"
      ? await (projectTestConfig as UserConfigFnPromise)(env)
      : projectTestConfig,
  ),
);
