test_suites:
  - name: semgrep
    script_path: /root/okta/odyssey/scripts
    sort_order: "1"
    timeout: "10"
    script_name: semgrep
    criteria: MERGE
    queue_name: small

  - name: release-odyssey
    task_name: RELEASE_ODYSSEY
    sort_order: 2
    queue_name: ci-queue-Jenga-Unit-v3
    criteria: MAINLINE
    trigger: AUTO
    params:
      DIST_TAG: "latest"
