test_suites:
  - name: "Build"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_path: /root/okta/odyssey/scripts
    sort_order: "4"
    steps:
      - event: SOURCE
        action: setup.sh
        name: Setup Environment
      - event: COMMAND
        action: yarn build
        name: Build Packages
    timeout: "20"

  - name: "Code Coverage"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_name: odyssey-code-coverage
    script_path: /root/okta/odyssey/scripts
    sort_order: "6"
    timeout: "20"

  - name: "Interaction Test"
    criteria: MERGE
    queue_name: ci-queue-prodJenga-Ubuntu20 # Playwright only works with certain distros of Linux
    script_path: /root/okta/odyssey/scripts
    script_name: interaction-test
    sort_order: "5"
    timeout: "20"

  - name: "Lint"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_path: /root/okta/odyssey/scripts
    sort_order: "1"
    steps:
      - event: SOURCE
        action: setup.sh
        name: Setup Environment
      - event: COMMAND
        action: yarn lint
        name: Lint Code
    timeout: "20"

  - name: "Publish Package"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_name: publish-packages
    script_path: /root/okta/odyssey/scripts
    sort_order: "8"
    timeout: "15"

  - name: "Publish Storybook"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_name: publish-storybook
    script_path: /root/okta/odyssey/scripts
    sort_order: "9"
    timeout: "15"

  - name: "Semgrep"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_name: semgrep
    script_path: /root/okta/odyssey/scripts
    sort_order: "10"
    timeout: "10"

  - name: "Test"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_name: unit-test
    script_path: /root/okta/odyssey/scripts
    sort_order: "3"
    timeout: "20"

  - name: "Typecheck"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_path: /root/okta/odyssey/scripts
    sort_order: "2"
    steps:
      - event: SOURCE
        action: setup.sh
        name: Setup Environment
      - event: COMMAND
        action: yarn typecheck
        name: Typecheck Code
    timeout: "20"

  - name: "Visual Regression Test"
    criteria: MERGE
    queue_name: ci-queue-productionJenga-AL2023
    script_name: visual-regression-test
    script_path: /root/okta/odyssey/scripts
    sort_order: "7"
    timeout: "20"
