test_suites:
  - name: "build"
    abort_commit_on_failure: true
    criteria: MERGE
    # prereq_test_suite_name:
    #   - "test"
    # queue_name: ci-queue-productionJenga-AL2023
    queue_name: small
    script_name: build
    script_path: /root/okta/odyssey/scripts
    sort_order: "4"
    timeout: "20"

  - name: "lint"
    abort_commit_on_failure: true
    criteria: MERGE
    queue_name: small
    script_name: lint
    script_path: /root/okta/odyssey/scripts
    sort_order: "1"
    timeout: "20"

  - name: "test"
    abort_commit_on_failure: true
    criteria: MERGE
    queue_name: small
    script_name: test
    script_path: /root/okta/odyssey/scripts
    sort_order: "3"
    timeout: "20"

  - name: "typecheck"
    abort_commit_on_failure: true
    criteria: MERGE
    queue_name: small
    script_name: typecheck
    script_path: /root/okta/odyssey/scripts
    sort_order: "2"
    timeout: "20"

  - name: semgrep
    criteria: MERGE
    queue_name: small
    script_name: semgrep
    script_path: /root/okta/odyssey/scripts
    sort_order: "1"
    timeout: "10"
