test_suites:
  - name: "Build"
    abort_commit_on_failure: true
    criteria: MERGE
    queue_name: al2023
    script_path: /root/okta/odyssey/scripts
    sort_order: "4"
    steps:
      - event: SOURCE
        action: setup.sh
        name: Setup Environment
      - event: COMMAND
        action: yarn build
        name: Build Packages
    timeout: "20"

  - name: "Code Coverage"
    abort_commit_on_failure: true
    criteria: OPTIONAL
    # Playwright only works with certain distros of Linux
    queue_name: ci-queue-prodJenga-Ubuntu20
    script_path: /root/okta/odyssey/scripts
    script_name: code-coverage
    sort_order: "6"
    timeout: "20"

  - name: "Interaction Test"
    abort_commit_on_failure: true
    criteria: MERGE
    # Playwright only works with certain distros of Linux
    queue_name: ci-queue-prodJenga-Ubuntu20
    script_path: /root/okta/odyssey/scripts
    script_name: interaction-test
    sort_order: "5"
    timeout: "20"

  - name: "Lint"
    abort_commit_on_failure: true
    criteria: MERGE
    queue_name: al2023
    script_path: /root/okta/odyssey/scripts
    sort_order: "1"
    steps:
      - event: SOURCE
        action: setup.sh
        name: Setup Environment
      - event: COMMAND
        action: yarn lint
        name: Lint Code
    timeout: "20"

  - name: "Publish Package"
    abort_commit_on_failure: true
    script_path: /root/okta/odyssey/scripts
    sort_order: "8"
    timeout: "15"
    script_name: publish-package
    criteria: MERGE
    prereq_test_suite_names:
      - "Build"
    queue_name: al2023

  - name: "Publish Storybook"
    abort_commit_on_failure: true
    script_path: /root/okta/odyssey/scripts
    sort_order: "9"
    timeout: "15"
    script_name: publish-storybook
    criteria: MERGE
    prereq_test_suite_names:
      - "Build"
    queue_name: al2023

  - name: "Semgrep"
    criteria: MERGE
    queue_name: al2023
    script_name: semgrep
    script_path: /root/okta/odyssey/scripts
    sort_order: "7"
    timeout: "10"

  - name: "Test"
    abort_commit_on_failure: true
    script_path: /root/okta/odyssey/scripts
    sort_order: "3"
    script_name: unit-test
    criteria: MERGE
    queue_name: al2023
    timeout: "20"

  - name: "Typecheck"
    abort_commit_on_failure: true
    criteria: MERGE
    queue_name: al2023
    script_path: /root/okta/odyssey/scripts
    sort_order: "2"
    steps:
      - event: SOURCE
        action: setup.sh
        name: Setup Environment
      - event: COMMAND
        action: yarn typecheck
        name: Typecheck Code
    timeout: "20"

  - name: "Visual Regression Test"
    abort_commit_on_failure: true
    script_path: /root/okta/odyssey/scripts
    sort_order: "7"
    script_name: visual-regression-test
    criteria: MERGE
    queue_name: ci-queue-prodJenga-Ubuntu20
    timeout: "20"
