promotion:
  /(master|main)/:
    - merge
    - tag
    - npm_promotion
    - release_notes
    - bump_versions
  /(^release$|^preview$|^((?:[0-9]+\.)+[0-9]+)(-[a-zA-Z]{2,3}[0-9]+)?$)/:
    - tag
    - npm_promotion
    - release_notes
  /(^hotfix)/:
    - artifactory_promotion
  default:
    - fail
