enableStrictSsl: false

nodeLinker: pnp

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  okta:
    npmRegistryServer: "${OKTA_NPM_REGISTRY_SERVER-https://registry.yarnpkg.com}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
