enableStrictSsl: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  okta:
    npmRegistryServer: "${OKTA_NPM_REGISTRY_SERVER-https://registry.yarnpkg.com}"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
