compressionLevel: mixed

enableGlobalCache: false

# enableStrictSsl: false # Uncomment this if having issues installing Yarn updates.

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.9.1.cjs
