yarnPath: .yarn/releases/yarn-3.2.0.cjs
npmRegistryServer: "https://registry.yarnpkg.com"
enableStrictSsl: false
nodeLinker: "node-modules"
npmScopes:
  okta:
    npmRegistryServer: ${YARN_OKTA_NPM_REGISTRY_SERVER-}
