/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonActionTypes,
  ButtonSizes,
  ButtonTypes,
} from './types';

export namespace Components {
  interface OdsButton {
    'actionType': ButtonActionTypes;
    'disabled': boolean;
    'href': string;
    'size': ButtonSizes;
    'type': ButtonTypes;
  }
}

declare global {


  interface HTMLOdsButtonElement extends Components.OdsButton, HTMLStencilElement {}
  var HTMLOdsButtonElement: {
    prototype: HTMLOdsButtonElement;
    new (): HTMLOdsButtonElement;
  };
  interface HTMLElementTagNameMap {
    'ods-button': HTMLOdsButtonElement;
  }
}

declare namespace LocalJSX {
  interface OdsButton {
    'actionType'?: ButtonActionTypes;
    'disabled'?: boolean;
    'href'?: string;
    'onOdsButtonFocus'?: (event: CustomEvent<any>) => void;
    'size'?: ButtonSizes;
    'type'?: ButtonTypes;
  }

  interface IntrinsicElements {
    'ods-button': OdsButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ods-button': LocalJSX.OdsButton & JSXBase.HTMLAttributes<HTMLOdsButtonElement>;
    }
  }
}


