/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface OdsTag {}
}

declare global {


  interface HTMLOdsTagElement extends Components.OdsTag, HTMLStencilElement {}
  var HTMLOdsTagElement: {
    prototype: HTMLOdsTagElement;
    new (): HTMLOdsTagElement;
  };
  interface HTMLElementTagNameMap {
    'ods-tag': HTMLOdsTagElement;
  }
}

declare namespace LocalJSX {
  interface OdsTag {}

  interface IntrinsicElements {
    'ods-tag': OdsTag;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ods-tag': LocalJSX.OdsTag & JSXBase.HTMLAttributes<HTMLOdsTagElement>;
    }
  }
}


