// DO NOT EDIT THIS FILE!
// This is the vite.config.ts file provided by the core-gen4 stack. Do not edit this; instead, place any custom configuration settings
// in the `vite.config.project.ts` file. If this file is modified, you are on your own and results of using the stack's vite config
// cannot be supported.

import stackConfig from "@okta/ui-stacks-component-libraries-odyssey-contributions/dist/configs/vite.config.js";
import { defineConfig, mergeConfig, type UserConfigFnPromise } from "vite";

import projectConfig from "./vite.config.project.js";

// Merge, in this order:
// - the stack's vite.config.js
// - the project's vite.config.project.js
export default defineConfig(async (env) =>
  mergeConfig(
    stackConfig,
    typeof projectConfig === "function"
      ? await (projectConfig as UserConfigFnPromise)(env)
      : projectConfig,
  ),
);
