/*!
 * Copyright (c) 2025-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

/*
 *************************************************************************
 *  NOTICE: THIS FILE WAS AUTO-GENERATED BY THE `generate:i18n` SCRIPT.  *
 *************************************************************************
 */

import { translation as defaultTranslation } from "../properties/ts/odyssey-react-mui.js";

export const defaultLanguageCode = "en" as const;

/**
 * The namespace for the odyssey-react-mui package.
 */
export const namespace = "odyssey-react-mui" as const;
export type i18nNamespace = typeof namespace;

/**
 * Defines the shape of all translation keys for the Odyssey namespace.
 * It's derived from the default (en) translation file,
 * which acts as the source of truth for all available keys.
 */
export type i18nResourceType = typeof defaultTranslation;

/**
 * Supported languages for translations for the odyssey-react-mui package.
 */
export type SupportedLanguages =
  | "cs"
  | "da"
  | "de"
  | "el"
  | "en"
  | "es"
  | "eu"
  | "fi"
  | "fr"
  | "ht"
  | "hu"
  | "id"
  | "it"
  | "ja"
  | "ko"
  | "ms"
  | "nb"
  | "nl_NL"
  | "ok_PL"
  | "ok_SK"
  | "pl"
  | "pt_BR"
  | "ro"
  | "ru"
  | "sv"
  | "th"
  | "tr"
  | "uk"
  | "vi"
  | "zh_CN"
  | "zh_TW";

export type ResourceRecord = Record<
  SupportedLanguages,
  Partial<Record<keyof i18nResourceType, string>>
>;
