/*!
 * Copyright (c) 2026-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated; DO NOT EDIT.

export const iconNames = [
  "Add",
  "AddCircle",
  "Apps",
  "AppsSelected",
  "ArrowBottom",
  "ArrowDown",
  "ArrowLeft",
  "ArrowLowerLeft",
  "ArrowLowerRight",
  "ArrowRight",
  "ArrowTop",
  "ArrowUnsorted",
  "ArrowUp",
  "ArrowUpperLeft",
  "ArrowUpperRight",
  "Bug",
  "Calendar",
  "Call",
  "Chat",
  "Check",
  "CheckCircleFilled",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "Clock",
  "Close",
  "CloseCircleFilled",
  "CollapseLeft",
  "CollapseRight",
  "Copy",
  "Customizations",
  "CustomizationsSelected",
  "DangerDiamond",
  "DangerDiamondFilled",
  "Delete",
  "Deny",
  "Devices",
  "Directory",
  "DirectorySelected",
  "Documentation",
  "Download",
  "DragIndicator",
  "Edit",
  "ExpandLeft",
  "ExpandRight",
  "ExternalLink",
  "Filter",
  "Folder",
  "Globe",
  "Grid",
  "Group",
  "Happy",
  "Hide",
  "Home",
  "HomeSelected",
  "IdentityGovernance",
  "IdentityGovernanceSelected",
  "InformationCircle",
  "InformationCircleFilled",
  "Link",
  "List",
  "Lock",
  "Menu",
  "More",
  "Neutral",
  "Notification",
  "Pause",
  "QuestionCircle",
  "QuestionCircleFilled",
  "Refresh",
  "Reports",
  "ReportsSelected",
  "Reset",
  "Resume",
  "Sad",
  "Same",
  "Search",
  "Security",
  "SecuritySelected",
  "Send",
  "Server",
  "Settings",
  "SettingsSelected",
  "Show",
  "Sparkle",
  "Subtract",
  "Sync",
  "ThumbsDown",
  "ThumbsUp",
  "Unlock",
  "Upload",
  "User",
  "Video",
  "Warning",
  "WarningFilled",
  "Workflows",
  "WorkflowsSelected",
] as const satisfies readonly string[];

export type IconName = (typeof iconNames)[number];
