# replace default config

multipass: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeXMLNS: false
  - removeEditorsNSData: true
  - cleanupAttrs: true
  - inlineStyles: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - cleanupIDs: true
  - prefixIds: false
  - removeRasterImages: true
  - removeUselessDefs: true
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - convertColors:
      currentColor: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: false
  - cleanupEnableBackground: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: true
  - convertEllipseToCircle: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - convertPathData: false
  - convertTransform: false
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - mergePaths: true
  - removeUnusedNS: true
  - sortAttrs: false
  - sortDefsChildren: true
  - removeTitle: false
  - removeDesc: false
  - removeDimensions: true
  - removeAttrs: false
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement:
      classNames: ["ods-icon"]
  - removeStyleElement: true
  - removeScriptElement: true
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: false
  - reusePaths: false
