/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonActionTypes, ButtonSizes, ButtonTypes } from "./types";
export namespace Components {
    interface OButton {
        "actionType": ButtonActionTypes;
        "disabled": boolean;
        "href": string;
        "icon": string;
        "size": ButtonSizes;
        "type": ButtonTypes;
    }
    interface OIcon {
        "name": string;
        "size": 'x-small' | 'small' | 'medium'| 'large' | 'x-large';
    }
}
declare global {
    interface HTMLOButtonElement extends Components.OButton, HTMLStencilElement {
    }
    var HTMLOButtonElement: {
        prototype: HTMLOButtonElement;
        new (): HTMLOButtonElement;
    };
    interface HTMLOIconElement extends Components.OIcon, HTMLStencilElement {
    }
    var HTMLOIconElement: {
        prototype: HTMLOIconElement;
        new (): HTMLOIconElement;
    };
    interface HTMLElementTagNameMap {
        "o-button": HTMLOButtonElement;
        "o-icon": HTMLOIconElement;
    }
}
declare namespace LocalJSX {
    interface OButton {
        "actionType"?: ButtonActionTypes;
        "disabled"?: boolean;
        "href"?: string;
        "icon"?: string;
        "onOButtonFocus"?: (event: CustomEvent<any>) => void;
        "size"?: ButtonSizes;
        "type"?: ButtonTypes;
    }
    interface OIcon {
        "name"?: string;
        "size"?: 'x-small' | 'small' | 'medium'| 'large' | 'x-large';
    }
    interface IntrinsicElements {
        "o-button": OButton;
        "o-icon": OIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "o-button": LocalJSX.OButton & JSXBase.HTMLAttributes<HTMLOButtonElement>;
            "o-icon": LocalJSX.OIcon & JSXBase.HTMLAttributes<HTMLOIconElement>;
        }
    }
}
