/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type AlertCircleIconProps = SvgIconNoChildrenProps;

export const AlertCircleIcon = forwardRef<SVGSVGElement, AlertCircleIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M15 8C15 11.866 11.866 15 8 15C4.13401 15 1 11.866 1 8C1 4.13401 4.13401 1 8 1C11.866 1 15 4.13401 15 8ZM8 16C12.4183 16 16 12.4183 16 8C16 3.58172 12.4183 0 8 0C3.58172 0 0 3.58172 0 8C0 12.4183 3.58172 16 8 16ZM8.4991 4.00121V4.50121V8.50121C8.4991 8.77735 8.27524 9.00121 7.9991 9.00121C7.72296 9.00121 7.4991 8.77735 7.4991 8.50121V4.50121V4.00121H8.4991ZM7.9991 12.2512C8.41331 12.2512 8.7491 11.9154 8.7491 11.5012C8.7491 11.087 8.41331 10.7512 7.9991 10.7512C7.58489 10.7512 7.2491 11.087 7.2491 11.5012C7.2491 11.9154 7.58489 12.2512 7.9991 12.2512Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

AlertCircleIcon.displayName = "AlertCircleIcon";
