/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type AlertTriangleFilledIconProps = SvgIconNoChildrenProps;

export const AlertTriangleFilledIcon = forwardRef<
  SVGSVGElement,
  AlertTriangleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M13.983 14.647c-.512.353-1.35.353-3.026.353H5.042c-1.675 0-2.513 0-3.025-.353a2 2 0 0 1-.839-1.322c-.101-.614.256-1.372.97-2.888l2.957-6.284C6.029 2.189 6.49 1.207 7.125.898a2 2 0 0 1 1.75 0c.634.309 1.096 1.29 2.02 3.255l2.958 6.284c.713 1.516 1.07 2.274.969 2.888a2 2 0 0 1-.839 1.322ZM8 10a.5.5 0 0 1-.5-.5V5h1v4.5a.5.5 0 0 1-.5.5Zm0 3a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

AlertTriangleFilledIcon.displayName = "AlertTriangleFilledIcon";
