/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type AlertTriangleFilledIconProps = SvgIconNoChildrenProps;

export const AlertTriangleFilledIcon = forwardRef<
  SVGSVGElement,
  AlertTriangleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M14.91 15.639c-.516.361-1.373.361-3.088.361H4.178c-1.715 0-2.572 0-3.088-.361a2 2 0 0 1-.832-1.347c-.093-.623.29-1.39 1.058-2.923L5.685 2.63C6.43 1.14 6.803.395 7.307.156a1.618 1.618 0 0 1 1.386 0c.504.239.877.984 1.622 2.474l4.37 8.739c.766 1.533 1.15 2.3 1.057 2.923a2 2 0 0 1-.832 1.347ZM8.5 5v4.5a.5.5 0 1 1-1 0v-4.5h1Zm-.5 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

AlertTriangleFilledIcon.displayName = "AlertTriangleFilledIcon";
