/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ArrowUpDownIconProps = SvgIconNoChildrenProps;

export const ArrowUpDownIcon = forwardRef<SVGSVGElement, ArrowUpDownIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M5 12V3.707l2.646 2.647.708-.708-3.5-3.5a.5.5 0 0 0-.708 0l-3.5 3.5.708.708L4 3.707V12h1Zm6-8v8.293L8.354 9.646l-.708.708 3.5 3.5a.5.5 0 0 0 .708 0l3.5-3.5-.707-.708L12 12.293V4h-1Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

ArrowUpDownIcon.displayName = "ArrowUpDownIcon";
