/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ArrowUpperRightIconProps = SvgIconNoChildrenProps;

export const ArrowUpperRightIcon = forwardRef<
  SVGSVGElement,
  ArrowUpperRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M11.293 4H4V3h8.476a.51.51 0 0 1 .51.51V12h-1V4.721l-8.632 8.633-.708-.708L11.293 4Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

ArrowUpperRightIcon.displayName = "ArrowUpperRightIcon";
