/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ArrowUpDownIconProps = SvgIconNoChildrenProps;

export const ArrowUpDownIcon = forwardRef<SVGSVGElement, ArrowUpDownIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5.00001 12V3.70711L7.64645 6.35355L8.35356 5.64645L4.85356 2.14645C4.6583 1.95118 4.34172 1.95118 4.14646 2.14645L0.646454 5.64645L1.35356 6.35355L4.00001 3.70711L4.00001 12H5.00001ZM11 4L11 12.2929L8.35357 9.64644L7.64647 10.3536L11.1465 13.8536C11.3417 14.0488 11.6583 14.0488 11.8536 13.8536L15.3536 10.3536L14.6465 9.64644L12 12.2929L12 4L11 4Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ArrowUpDownIcon.displayName = "ArrowUpDownIcon";
