/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ArrowLowerRightIconProps = SvgIconNoChildrenProps;

export const ArrowLowerRightIcon = forwardRef<
  SVGSVGElement,
  ArrowLowerRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M11.294 12.002 2.646 3.354l.708-.708 8.62 8.62.011-7.267 1 .002-.014 8.49a.51.51 0 0 1-.51.509l-8.432.014-.001-1 7.266-.012Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

ArrowLowerRightIcon.displayName = "ArrowLowerRightIcon";
