/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type BugIconProps = SvgIconNoChildrenProps;

export const BugIcon = forwardRef<SVGSVGElement, BugIconProps>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M4.53544 3C4.77806 1.30385 6.23676 0 8 0C9.76324 0 11.2219 1.30385 11.4646 3H12.5H13H16V4H13V8.04001L15.6581 8.92605L15.3419 9.87473L13 9.0941V10C13 10.9171 12.7531 11.7765 12.3221 12.5154L13.8536 14.0468L13.1464 14.7539L11.7264 13.3339C10.8108 14.3565 9.48058 15 8 15C6.51942 15 5.18915 14.3565 4.27363 13.3339L2.85355 14.7539L2.14645 14.0468L3.67787 12.5154C3.2469 11.7765 3 10.9171 3 10V9.0941L0.658114 9.87473L0.341886 8.92605L3 8.04001V4H0V3H3H3.5H4.53544ZM10.45 3C10.2184 1.85888 9.20948 1 8 1C6.79052 1 5.78164 1.85888 5.55001 3H10.45ZM7.5 4H4V10C4 12.0398 5.52684 13.723 7.5 13.9691V4ZM8.5 13.9691V4H12V10C12 12.0398 10.4732 13.723 8.5 13.9691Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

BugIcon.displayName = "BugIcon";
