/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type BugIconProps = SvgIconNoChildrenProps;

export const BugIcon = forwardRef<SVGSVGElement, BugIconProps>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M4.535 3a3.5 3.5 0 0 1 6.93 0H16v1h-3v4.04l2.658.886-.316.949L13 9.095V10c0 .917-.247 1.777-.678 2.515l1.532 1.532-.708.707-1.42-1.42A4.988 4.988 0 0 1 8 15c-1.48 0-2.81-.643-3.726-1.666l-1.42 1.42-.708-.707 1.532-1.532A4.977 4.977 0 0 1 3 10v-.906l-2.342.78-.316-.948L3 8.04V4H0V3h4.535Zm5.915 0a2.5 2.5 0 0 0-4.9 0h4.9ZM7.5 4H4v6a4 4 0 0 0 3.5 3.97V4Zm1 9.97V4H12v6a4 4 0 0 1-3.5 3.97Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

BugIcon.displayName = "BugIcon";
