/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type CalendarIconProps = SvgIconNoChildrenProps;

export const CalendarIcon = forwardRef<SVGSVGElement, CalendarIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M5 4V3H2V6H14V3H11V4H10V3H6V4H5ZM10 2H6V0H5V2H1.5H1V2.5V12.1V12.1207V12.1207C0.999994 12.5231 0.999989 12.8553 1.0221 13.1259C1.04506 13.407 1.09434 13.6653 1.21799 13.908C1.40973 14.2843 1.7157 14.5903 2.09202 14.782C2.33469 14.9057 2.59304 14.9549 2.87409 14.9779C3.14468 15 3.47686 15 3.87934 15H3.9H12.1H12.1207C12.5231 15 12.8553 15 13.1259 14.9779C13.407 14.9549 13.6653 14.9057 13.908 14.782C14.2843 14.5903 14.5903 14.2843 14.782 13.908C14.9057 13.6653 14.9549 13.407 14.9779 13.1259C15 12.8553 15 12.5231 15 12.1207V12.1V2.5V2H14.5H11V0H10V2ZM2 7V12.1C2 12.5283 2.00039 12.8194 2.01878 13.0445C2.03669 13.2637 2.06915 13.3758 2.10899 13.454C2.20487 13.6422 2.35785 13.7951 2.54601 13.891C2.62421 13.9309 2.73631 13.9633 2.95552 13.9812C3.18056 13.9996 3.47171 14 3.9 14H12.1C12.5283 14 12.8194 13.9996 13.0445 13.9812C13.2637 13.9633 13.3758 13.9309 13.454 13.891C13.6422 13.7951 13.7951 13.6422 13.891 13.454C13.9309 13.3758 13.9633 13.2637 13.9812 13.0445C13.9996 12.8194 14 12.5283 14 12.1V7H2Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

CalendarIcon.displayName = "CalendarIcon";
