/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type CallIconProps = SvgIconNoChildrenProps;

export const CallIcon = forwardRef<SVGSVGElement, CallIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M8 1c3.796 0 7 3.183 7 7h1c0-4.371-3.653-8-8-8v1ZM3.703 2.689a.5.5 0 0 0-.691-.072 2.663 2.663 0 0 0-.168.163l-.448.45a4.795 4.795 0 0 0-.027 6.737l3.5 3.573a4.86 4.86 0 0 0 6.857.087l.424-.411c.12-.117.147-.144.16-.161a.5.5 0 0 0-.06-.692 2.656 2.656 0 0 0-.186-.13l-2.2-1.491a7.72 7.72 0 0 0-.424-.277.55.55 0 0 0-.165-.073.5.5 0 0 0-.268.023.552.552 0 0 0-.15.1c-.09.074-.2.178-.371.343l-.181.174-.014.013c-.19.182-.353.339-.498.457-.154.125-.32.235-.522.297a1.5 1.5 0 0 1-.925-.018 1.526 1.526 0 0 1-.51-.315c-.141-.124-.299-.287-.481-.476l-.014-.014-1.403-1.451-.014-.014c-.18-.186-.335-.347-.453-.49a1.526 1.526 0 0 1-.296-.514 1.5 1.5 0 0 1 .007-.916c.065-.199.177-.36.303-.51.12-.142.277-.3.46-.484l.013-.013.145-.145c.167-.169.274-.276.35-.365a.548.548 0 0 0 .102-.148.5.5 0 0 0 .028-.267.548.548 0 0 0-.07-.166 7.692 7.692 0 0 0-.267-.428L3.833 2.884a2.659 2.659 0 0 0-.13-.195Zm-1.307-.86a1.5 1.5 0 0 1 2.072.217c.06.072.12.163.189.27l.016.024L6.086 4.52l.009.014c.117.181.22.34.295.478.081.147.149.302.179.48a1.5 1.5 0 0 1-.084.8 1.513 1.513 0 0 1-.274.433c-.102.12-.235.253-.387.406l-.012.012-.145.145c-.2.201-.328.33-.418.437a.568.568 0 0 0-.117.177.5.5 0 0 0-.003.305c.009.027.03.075.115.178.089.108.215.24.412.444L7.06 10.28c.2.207.33.34.436.433.102.09.15.113.176.122a.5.5 0 0 0 .308.006.57.57 0 0 0 .181-.115c.11-.09.244-.218.452-.417l.18-.173.012-.012c.157-.15.293-.28.415-.381.13-.108.269-.203.438-.267a1.5 1.5 0 0 1 .804-.068c.178.034.331.105.477.19.137.078.293.184.473.305l.014.01 2.2 1.491.022.016c.103.07.19.128.259.188a1.5 1.5 0 0 1 .182 2.074c-.058.071-.134.145-.222.23l-.02.02-.424.412a5.86 5.86 0 0 1-8.268-.105l-3.5-3.573a5.795 5.795 0 0 1 .032-8.141l.448-.451.02-.02c.09-.09.166-.168.24-.226ZM11.5 8c0-1.906-1.604-3.5-3.5-3.5v-1c2.447 0 4.5 2.04 4.5 4.5h-1Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

CallIcon.displayName = "CallIcon";
