/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type CheckIconProps = SvgIconNoChildrenProps;

export const CheckIcon = forwardRef<SVGSVGElement, CheckIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M15.3535 3.35361L6.35359 12.3536C6.25982 12.4473 6.13265 12.5 6.00004 12.5C5.86743 12.5 5.74025 12.4473 5.64648 12.3536L0.646484 7.35355L1.35359 6.64645L6.00004 11.2929L14.6464 2.64651L15.3535 3.35361Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

CheckIcon.displayName = "CheckIcon";
