/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type CollapseRightIconProps = SvgIconNoChildrenProps;

export const CollapseRightIcon = forwardRef<
  SVGSVGElement,
  CollapseRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M16 16H15V0H16V16ZM12.2146 8.5H0V7.5H12.2146L7.16214 2.86858L7.83786 2.13142L13.825 7.61963L13.8339 7.62786C13.8382 7.63198 13.8482 7.64155 13.8599 7.65427C13.8824 7.67867 13.9348 7.73935 13.9674 7.834C14.0045 7.94157 14.0045 8.05843 13.9674 8.166C13.9348 8.26065 13.8824 8.32133 13.8599 8.34573C13.8482 8.35845 13.8382 8.36802 13.8339 8.37214L13.825 8.38037L7.83786 13.8686L7.16214 13.1314L12.2146 8.5ZM13.1516 8.35893C13.1517 8.35899 13.151 8.35832 13.1493 8.35678L13.1481 8.35575C13.1502 8.35771 13.1515 8.35887 13.1516 8.35893ZM13.1481 7.64425C13.1519 7.64068 13.153 7.63979 13.1493 7.64322L13.1481 7.64425Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

CollapseRightIcon.displayName = "CollapseRightIcon";
