/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type CollapseLeftIconProps = SvgIconNoChildrenProps;

export const CollapseLeftIcon = forwardRef<
  SVGSVGElement,
  CollapseLeftIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M1 0V16H0V0H1ZM3.7854 7.5H16V8.5H3.7854L8.83786 13.1314L8.16214 13.8686L2.175 8.38037L2.16615 8.37214C2.16179 8.36802 2.15178 8.35845 2.14006 8.34573C2.11758 8.32133 2.06515 8.26065 2.03257 8.166C1.99554 8.05843 1.99554 7.94157 2.03257 7.834C2.06515 7.73935 2.11758 7.67867 2.14006 7.65427C2.15178 7.64155 2.16179 7.63198 2.16615 7.62786L2.175 7.61963L8.16214 2.13142L8.83786 2.86858L3.7854 7.5ZM2.85186 8.35575L2.85073 8.35678C2.84923 8.35816 2.84851 8.35884 2.84842 8.35893C2.8483 8.35906 2.8496 8.35789 2.85186 8.35575ZM2.85185 7.64425L2.85073 7.64322C2.847 7.6398 2.84808 7.64068 2.85185 7.64425Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

CollapseLeftIcon.displayName = "CollapseLeftIcon";
