/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type DangerDiamondFilledIconProps = SvgIconNoChildrenProps;

export const DangerDiamondFilledIcon = forwardRef<
  SVGSVGElement,
  DangerDiamondFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M.586 6.583 6.583.586a2 2 0 0 1 2.829 0l6.01 6.011a2 2 0 0 1 0 2.828l-5.996 5.997a2 2 0 0 1-2.828 0L.586 9.412a2 2 0 0 1 0-2.83Zm6.932 1.89V4.166h1v4.307a.5.5 0 0 1-1 0Zm1.217 2.87a.717.717 0 1 1-1.435 0 .717.717 0 0 1 1.435 0Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

DangerDiamondFilledIcon.displayName = "DangerDiamondFilledIcon";
