/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type DocumentationIconProps = SvgIconNoChildrenProps;

export const DocumentationIcon = forwardRef<
  SVGSVGElement,
  DocumentationIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M5.413 2c.333 0 .463 0 .587.014a2.5 2.5 0 0 1 1.5.708v10.824C6.89 13.21 6.203 13 5.5 13H1V2h4.413ZM8.06 14.983a.518.518 0 0 1-.362-.087l-.002-.001a.546.546 0 0 1-.033-.025l-.012-.01C7.025 14.33 6.246 14 5.5 14H0V1h5.442c.295 0 .48 0 .661.019a3.5 3.5 0 0 1 1.887.802 3.5 3.5 0 0 1 2.063-.816C10.148 1 10.245 1 10.399 1H16v13h-5.6c-.75 0-1.512.332-2.023.83l-.012.012a.587.587 0 0 1-.031.027l-.002.002a.512.512 0 0 1-.272.112Zm.44-1.477A3.946 3.946 0 0 1 10.4 13H15V2h-4.586c-.174 0-.242 0-.307.004a2.5 2.5 0 0 0-1.607.704v10.798ZM6 6H2V5h4v1Zm4 0h4V5h-4v1Zm-4 4H2V9h4v1Zm4 0h4V9h-4v1Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

DocumentationIcon.displayName = "DocumentationIcon";
