/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type DocumentationIconProps = SvgIconNoChildrenProps;

export const DocumentationIcon = forwardRef<
  SVGSVGElement,
  DocumentationIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M2 3H1v18h7.667c1.093 0 2.003.199 2.67.75l.004.002.015.012c.008.007.031.026.062.047l.003.002a1.012 1.012 0 0 0 .696.168c.3-.033.494-.192.522-.215l.003-.003a1.061 1.061 0 0 0 .075-.066C13.23 21.209 14.082 21 15.2 21H23V3h-8.932a2.798 2.798 0 0 0-2.106.953 3.825 3.825 0 0 0-.232-.226A2.866 2.866 0 0 0 9.822 3H2Zm9 3.562c0-.513-.219-1.001-.601-1.343A.866.866 0 0 0 9.822 5H3v14h5.667c.746 0 1.553.077 2.333.332V6.561Zm0 14.4V20.972v-.01Zm2 0v.005-.008.003Zm0-1.666c.736-.232 1.509-.296 2.2-.296H21V5h-6.932c-.209 0-.41.082-.559.228-.326.32-.509.756-.509 1.212v12.856ZM9 11H5V9h4v2Zm6 0h4V9h-4v2Zm4 4h-4v-2h4v2ZM5 15h4v-2H5v2Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

DocumentationIcon.displayName = "DocumentationIcon";
