/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type DownloadIconProps = SvgIconNoChildrenProps;

export const DownloadIcon = forwardRef<SVGSVGElement, DownloadIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M13.146 6.146 8.5 10.793V0h-1v10.793L2.854 6.146l-.708.708 5.5 5.5a.5.5 0 0 0 .708 0l5.5-5.5-.708-.708ZM2 12.3V11H1v1.321c0 .542 0 .98.029 1.333.03.365.093.685.243.981a2.5 2.5 0 0 0 1.093 1.092c.296.151.616.214.98.244C3.7 16 4.138 16 4.68 16H11.32c.542 0 .98 0 1.333-.029.365-.03.685-.093.981-.244a2.5 2.5 0 0 0 1.092-1.092c.151-.296.214-.616.244-.98.029-.355.029-.792.029-1.333V11h-1v1.3c0 .568 0 .964-.026 1.273-.024.303-.07.476-.138.608a1.5 1.5 0 0 1-.655.655c-.132.068-.305.114-.608.138-.309.026-.705.026-1.273.026H4.7c-.568 0-.964 0-1.273-.026-.302-.024-.476-.07-.608-.138a1.5 1.5 0 0 1-.656-.655c-.067-.132-.113-.305-.137-.608C2 13.264 2 12.868 2 12.3Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

DownloadIcon.displayName = "DownloadIcon";
