/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type DragHandleIconProps = SvgIconNoChildrenProps;

export const DragHandleIcon = forwardRef<SVGSVGElement, DragHandleIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M4.444 2.169a1 1 0 1 1 1.112 1.663 1 1 0 0 1-1.112-1.663Zm0 5a1 1 0 1 1 1.112 1.663 1 1 0 0 1-1.112-1.663ZM5 12a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm5.444-9.831a1 1 0 1 1 1.112 1.663 1 1 0 0 1-1.112-1.663ZM11 7a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm-.556 5.168a1 1 0 1 1 1.111 1.663 1 1 0 0 1-1.11-1.662Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

DragHandleIcon.displayName = "DragHandleIcon";
