/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EditIconProps = SvgIconNoChildrenProps;

export const EditIcon = forwardRef<SVGSVGElement, EditIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M10.99.085a1.73 1.73 0 0 1 1.07 0c.228.074.416.203.597.356.172.146.367.341.599.572l.014.014.7.7.014.013c.232.232.427.427.574.6.153.18.283.368.357.597a1.73 1.73 0 0 1 0 1.07 1.765 1.765 0 0 1-.356.597c-.147.173-.342.368-.573.6l-.014.013-8.633 8.637-.147.146H1V9.812l.146-.147L9.781 1.03l.014-.014c.231-.232.426-.427.598-.573.18-.153.37-.283.598-.357Zm.76.95a.73.73 0 0 0-.45.001c-.053.017-.126.055-.26.168-.137.117-.303.282-.552.532l-.765.764L12.5 5.276l.765-.766c.25-.25.415-.415.532-.553.113-.133.151-.207.168-.26a.73.73 0 0 0 0-.45c-.017-.053-.055-.127-.168-.26a10.595 10.595 0 0 0-.533-.553l-.7-.7a10.52 10.52 0 0 0-.553-.53c-.133-.113-.206-.151-.26-.168ZM2 10.226l7.016-7.017 2.777 2.775L4.778 13H2v-2.774ZM1 16h14v-1H1v1Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

EditIcon.displayName = "EditIcon";
