/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EditIconProps = SvgIconNoChildrenProps;

export const EditIcon = forwardRef<SVGSVGElement, EditIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M10.354 2.06a.5.5 0 0 0-.708 0L8.707 3 11 5.293l.94-.94a.5.5 0 0 0 0-.707l-1.586-1.585ZM2 9.708l6-6L10.293 6l-6 6H2V9.707Zm6.94-8.353a1.5 1.5 0 0 1 2.12 0l1.586 1.585a1.5 1.5 0 0 1 0 2.122l-7.792 7.793-.147.146H1V9.293l.146-.147L8.94 1.354ZM1 14v1h14v-1H1Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

EditIcon.displayName = "EditIcon";
