/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ExpandRightIconProps = SvgIconNoChildrenProps;

export const ExpandRightIcon = forwardRef<SVGSVGElement, ExpandRightIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M15 15V1h-1v14h1ZM1.845 8.357v.001Zm0-.714v-.001c-.004-.004-.003-.003 0 0ZM7.336 3.37 2.79 7.5H13v1H2.79l4.547 4.13-.672.74-5.492-4.988-.009-.008a.51.51 0 0 1 0-.747l.009-.009L6.664 2.63l.672.74Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

ExpandRightIcon.displayName = "ExpandRightIcon";
