/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ExpandLeftIconProps = SvgIconNoChildrenProps;

export const ExpandLeftIcon = forwardRef<SVGSVGElement, ExpandLeftIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M2 15V1H1v14h1Zm12.15-7.358c.003-.003.004-.004 0 0Zm0 .715v.001c.004.004.003.003 0 0ZM8.663 12.63l4.543-4.13H3v-1h10.207L8.664 3.37l.672-.74 5.487 4.988.01.008a.525.525 0 0 1 .134.207.51.51 0 0 1-.135.54l-.009.009-5.487 4.988-.672-.74Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

ExpandLeftIcon.displayName = "ExpandLeftIcon";
