/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ExpandRightIconProps = SvgIconNoChildrenProps;

export const ExpandRightIcon = forwardRef<SVGSVGElement, ExpandRightIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M16.5 16V0H15.5V16H16.5ZM0.845938 8.35678L0.847064 8.35575C0.84329 8.35932 0.842203 8.36021 0.845938 8.35678ZM0.847059 7.64425L0.845937 7.64322C0.842204 7.6398 0.843289 7.64068 0.847059 7.64425ZM6.83307 2.86858L1.78061 7.5H13.9952V8.5H1.78061L6.83307 13.1314L6.15735 13.8686L0.170213 8.38037L0.161355 8.37214C0.157002 8.36802 0.146992 8.35845 0.13527 8.34573C0.112784 8.32133 0.0603614 8.26065 0.0277811 8.16601C-0.00925018 8.05843 -0.00925018 7.94157 0.0277811 7.834C0.0603623 7.73935 0.112787 7.67867 0.135271 7.65427C0.146993 7.64155 0.157003 7.63198 0.161355 7.62786L0.170213 7.61963L6.15735 2.13142L6.83307 2.86858Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ExpandRightIcon.displayName = "ExpandRightIcon";
