/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ExpandLeftIconProps = SvgIconNoChildrenProps;

export const ExpandLeftIcon = forwardRef<SVGSVGElement, ExpandLeftIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M1 16V0H0V16H1ZM15.1541 7.64322L15.1529 7.64425C15.1567 7.64069 15.1578 7.6398 15.1541 7.64322ZM15.1529 8.35576L15.1541 8.35678C15.1578 8.36021 15.1567 8.35932 15.1529 8.35576ZM9.16693 13.1314L14.2194 8.5L2.00479 8.5V7.5L14.2194 7.5L9.16693 2.86858L9.84265 2.13142L15.8298 7.61963L15.8386 7.62786C15.843 7.63199 15.853 7.64155 15.8647 7.65427C15.8872 7.67867 15.9396 7.73935 15.9722 7.834C16.0093 7.94157 16.0093 8.05843 15.9722 8.16601C15.9396 8.26065 15.8872 8.32133 15.8647 8.34573C15.853 8.35845 15.843 8.36802 15.8386 8.37214L15.8298 8.38037L9.84265 13.8686L9.16693 13.1314Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ExpandLeftIcon.displayName = "ExpandLeftIcon";
