/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ExternalLinkIconProps = SvgIconNoChildrenProps;

export const ExternalLinkIcon = forwardRef<
  SVGSVGElement,
  ExternalLinkIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M7 2H13.2929L5.14645 10.1464L5.85355 10.8536L14 2.70711V8H15V1.516L14.9999 1.50443C14.9998 1.49863 14.9996 1.48531 14.9982 1.46872C14.9955 1.43613 14.9869 1.36177 14.9444 1.27846C14.8955 1.1825 14.8175 1.10448 14.7215 1.05559C14.6382 1.01314 14.5639 1.00446 14.5313 1.0018C14.5147 1.00044 14.5014 1.00017 14.4956 1.00008L14.484 1H7V2ZM11 14V7.13165L12 6.11602V14.5V15H11.5H1.5H1V14.5V4.5V4H1.5H9.88477L8.86914 5H2V14H11Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ExternalLinkIcon.displayName = "ExternalLinkIcon";
