/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ExternalLinkIconProps = SvgIconNoChildrenProps;

export const ExternalLinkIcon = forwardRef<
  SVGSVGElement,
  ExternalLinkIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M13.293 2H8V1h6.5a.5.5 0 0 1 .5.5V8h-1V2.707l-7.646 7.647-.708-.708L13.293 2ZM1.5 4H1v11h11V8h-1v6H2V5h6V4H1.5Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

ExternalLinkIcon.displayName = "ExternalLinkIcon";
