/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EyeIconProps = SvgIconNoChildrenProps;

export const EyeIcon = forwardRef<SVGSVGElement, EyeIconProps>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M8 14C2.13333 14 0 8 0 8C0 8 2.13333 2 8 2C13.8667 2 16 8 16 8C16 8 13.8667 14 8 14ZM1.31275 7.52282C1.21655 7.70834 1.1399 7.87027 1.08174 8C1.1399 8.12973 1.21655 8.29166 1.31275 8.47718C1.57952 8.99165 1.99021 9.67529 2.56403 10.3548C3.70892 11.7106 5.45266 13 8 13C10.5473 13 12.2911 11.7106 13.436 10.3548C14.0098 9.67529 14.4205 8.99165 14.6872 8.47718C14.7834 8.29166 14.8601 8.12973 14.9183 8C14.8601 7.87027 14.7834 7.70834 14.6872 7.52282C14.4205 7.00835 14.0098 6.32471 13.436 5.64518C12.2911 4.28939 10.5473 3 8 3C5.45266 3 3.70892 4.28939 2.56403 5.64518C1.99021 6.32471 1.57952 7.00835 1.31275 7.52282ZM5.5 8C5.5 6.61929 6.61929 5.5 8 5.5C9.38071 5.5 10.5 6.61929 10.5 8C10.5 9.38071 9.38071 10.5 8 10.5C6.61929 10.5 5.5 9.38071 5.5 8ZM8 4.5C6.067 4.5 4.5 6.067 4.5 8C4.5 9.933 6.067 11.5 8 11.5C9.933 11.5 11.5 9.933 11.5 8C11.5 6.067 9.933 4.5 8 4.5Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

EyeIcon.displayName = "EyeIcon";
