/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EyeIconProps = SvgIconNoChildrenProps;

export const EyeIcon = forwardRef<SVGSVGElement, EyeIconProps>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M8 14c-5.867 0-8-6-8-6s2.133-6 8-6 8 6 8 6-2.133 6-8 6ZM1.313 7.523A9.354 9.354 0 0 0 1.082 8a10.272 10.272 0 0 0 1.482 2.355C3.709 11.71 5.453 13 8 13s4.291-1.29 5.436-2.645A10.268 10.268 0 0 0 14.918 8a10.27 10.27 0 0 0-1.482-2.355C12.291 4.29 10.547 3 8 3S3.709 4.29 2.564 5.645c-.574.68-.984 1.363-1.251 1.878ZM5.5 8a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0ZM8 4.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

EyeIcon.displayName = "EyeIcon";
