/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EyeIconProps = SvgIconNoChildrenProps;

export const EyeIcon = forwardRef<SVGSVGElement, EyeIconProps>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M3.898 11.55C2.896 10.7 2.042 9.5 1.156 8c.886-1.5 1.74-2.7 2.742-3.55C4.969 3.538 6.24 3 8 3c1.76 0 3.03.539 4.102 1.45 1.002.85 1.856 2.05 2.742 3.55-.886 1.5-1.74 2.7-2.742 3.55C11.031 12.462 9.76 13 8 13c-1.76 0-3.03-.539-4.102-1.45ZM8 14c4 0 6-2.5 8-6-2-3.5-4-6-8-6S2 4.5 0 8c2 3.5 4 6 8 6Zm3-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm1 0a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

EyeIcon.displayName = "EyeIcon";
