/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EyeOffIconProps = SvgIconNoChildrenProps;

export const EyeOffIcon = forwardRef<SVGSVGElement, EyeOffIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="m3.125 10.96-.707.708C.705 9.982 0 8 0 8s2.133-6 8-6c1.29 0 2.398.29 3.344.742l-.758.757C9.835 3.19 8.976 3 8 3 5.453 3 3.709 4.29 2.564 5.645A10.273 10.273 0 0 0 1.082 8a10.272 10.272 0 0 0 1.482 2.355c.173.205.36.408.561.606Zm2.163-.748-1.406 1.406-.712.712L1 14.5l.707.707 2.3-2.299A7.617 7.617 0 0 0 8 14c5.867 0 8-6 8-6s-.847-2.382-2.941-4.145l1.648-1.648L14 1.5l-1.752 1.752-.724.724-1.312 1.312L9.5 6 6 9.5l-.712.712Zm.268-1.682-.796.796A3.5 3.5 0 0 1 9.326 4.76l-.796.796A2.5 2.5 0 0 0 5.557 8.53ZM8 13a6.643 6.643 0 0 1-3.262-.824l1.287-1.286a3.5 3.5 0 0 0 4.865-4.865l1.459-1.46c.41.338.771.707 1.087 1.08A10.27 10.27 0 0 1 14.918 8a10.268 10.268 0 0 1-1.482 2.355C12.291 11.71 10.547 13 8 13Zm0-2.5c-.456 0-.883-.122-1.25-.335l3.415-3.416A2.5 2.5 0 0 1 8 10.5Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

EyeOffIcon.displayName = "EyeOffIcon";
