/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type EyeOffIconProps = SvgIconNoChildrenProps;

export const EyeOffIcon = forwardRef<SVGSVGElement, EyeOffIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M11.2 2.675C10.286 2.24 9.24 2 8 2 4 2 2 4.5 0 8c.761 1.333 1.523 2.52 2.395 3.48l.708-.708C2.425 10.02 1.799 9.09 1.156 8c.886-1.5 1.74-2.7 2.742-3.55C4.969 3.538 6.24 3 8 3c.938 0 1.737.153 2.441.434l.76-.76Zm.899.516-.723.722.003.001-.926.926-.002-.002-.715.715.002.002-4.183 4.183-.002-.002-.715.715.002.002-1.026 1.026-.002-.002-.708.708.002.002-1.96 1.96.708.707 2.045-2.046C5.016 13.566 6.334 14 8 14c4 0 6-2.5 8-6-.961-1.682-1.922-3.133-3.106-4.187l1.96-1.96-.708-.707-2.045 2.046-.002-.001ZM4.315 9.56l.786-.786a3.004 3.004 0 0 1 3.673-3.673l.786-.786A4 4 0 0 0 4.316 9.56Zm7.87-5.039L11.16 5.547a4 4 0 0 1-5.613 5.613l-.926.926C5.54 12.668 6.62 13 8 13c1.76 0 3.03-.539 4.102-1.45 1.002-.85 1.856-2.05 2.742-3.55-.861-1.459-1.693-2.632-2.658-3.479Zm-1.74 1.74-4.183 4.184a3 3 0 0 0 4.184-4.184Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

EyeOffIcon.displayName = "EyeOffIcon";
