/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type FolderIconProps = SvgIconNoChildrenProps;

export const FolderIcon = forwardRef<SVGSVGElement, FolderIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M5.3 3.00005C5.76898 3.00005 5.90582 3.00456 6.02461 3.03849C6.14384 3.07254 6.2557 3.12847 6.35448 3.20342C6.4529 3.2781 6.53861 3.38486 6.82 3.76005L9.1 6.80005L9.25 7.00004H9.5H15V11.1C15 11.5283 14.9996 11.8195 14.9812 12.0445C14.9633 12.2637 14.9309 12.3758 14.891 12.454C14.7951 12.6422 14.6422 12.7952 14.454 12.8911C14.3758 12.9309 14.2637 12.9634 14.0445 12.9813C13.8194 12.9997 13.5283 13 13.1 13H2.9C2.47171 13 2.18056 12.9997 1.95552 12.9813C1.73631 12.9634 1.62421 12.9309 1.54601 12.8911C1.35785 12.7952 1.20487 12.6422 1.10899 12.454C1.06915 12.3758 1.03669 12.2637 1.01878 12.0445C1.00039 11.8195 1 11.5283 1 11.1V3.00005H5.3ZM15 6.00004H9.75L8.625 4.50005H15V6.00004ZM7.875 3.50005L7.62 3.16005L7.58308 3.11078L7.58308 3.11078C7.3552 2.80658 7.18316 2.57693 6.95895 2.4068C6.7614 2.25689 6.53768 2.14504 6.29923 2.07694C6.0286 1.99965 5.74165 1.99981 5.36157 2.00002L5.3 2.00005H0.500001H2.03704e-07V2.50005V11.1V11.1207V11.1207C-5.93566e-06 11.5232 -1.1002e-05 11.8554 0.0220975 12.126C0.0450601 12.407 0.0943423 12.6654 0.217988 12.908C0.409734 13.2844 0.715695 13.5903 1.09202 13.7821C1.33469 13.9057 1.59304 13.955 1.87409 13.9779C2.14468 14.0001 2.47686 14.0001 2.87934 14H2.9H13.1H13.1207C13.5231 14.0001 13.8553 14.0001 14.1259 13.9779C14.407 13.955 14.6653 13.9057 14.908 13.7821C15.2843 13.5903 15.5903 13.2844 15.782 12.908C15.9057 12.6654 15.9549 12.407 15.9779 12.126C16 11.8554 16 11.5232 16 11.1207V11.1V7.00004V6.50004V6.00004V4.00005V3.50005H15.5H7.875Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

FolderIcon.displayName = "FolderIcon";
