/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type FolderIconProps = SvgIconNoChildrenProps;

export const FolderIcon = forwardRef<SVGSVGElement, FolderIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M5.3 3c.469 0 .606.005.725.038a1 1 0 0 1 .33.165c.098.075.184.182.465.557L9.1 6.8l.15.2H15v4.1c0 .428 0 .72-.019.944-.018.22-.05.332-.09.41a1 1 0 0 1-.437.437c-.078.04-.19.072-.41.09A12.93 12.93 0 0 1 13.1 13H2.9c-.428 0-.72 0-.944-.019-.22-.018-.332-.05-.41-.09a1 1 0 0 1-.437-.437c-.04-.078-.072-.19-.09-.41A12.924 12.924 0 0 1 1 11.1V3h4.3ZM15 6H9.75L8.625 4.5H15V6ZM7.875 3.5l-.255-.34-.037-.05c-.228-.303-.4-.533-.624-.703a2 2 0 0 0-.66-.33C6.03 2 5.742 2 5.362 2H0v9.12c0 .403 0 .735.022 1.006.023.281.072.54.196.782a2 2 0 0 0 .874.874c.243.124.501.173.782.196.27.022.603.022 1.005.022H13.12c.403 0 .735 0 1.006-.022.281-.023.54-.072.782-.196a2 2 0 0 0 .874-.874c.124-.243.173-.501.196-.782.022-.27.022-.603.022-1.005V3.5H7.875Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

FolderIcon.displayName = "FolderIcon";
