/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type GlobeIconProps = SvgIconNoChildrenProps;

export const GlobeIcon = forwardRef<SVGSVGElement, GlobeIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M1.01758 7.5C1.24188 4.32187 3.58776 1.7295 6.64756 1.13054C5.21402 2.83792 4.52547 5.15185 4.5007 7.5H1.01758ZM8.00023 1.1595C6.36443 2.66301 5.52894 5.00708 5.50074 7.5H10.4997C10.4715 5.00708 9.63603 2.66301 8.00023 1.1595ZM10.4681 8.5H5.5324C5.70327 10.7964 6.54721 13.0732 8.00023 14.76C9.45326 13.0732 10.2972 10.7964 10.4681 8.5ZM9.16862 14.9029C10.5398 13.0827 11.3136 10.7849 11.4706 8.5H14.9824C14.7536 11.7415 12.3179 14.3736 9.16862 14.9029ZM11.4998 7.5C11.475 5.1519 10.7865 2.83802 9.353 1.13065C12.4125 1.72981 14.7581 4.32206 14.9824 7.5H11.4998ZM1.01758 8.5H4.52991C4.68685 10.7849 5.46065 13.0828 6.83192 14.903C3.6824 14.3739 1.24636 11.7417 1.01758 8.5ZM8 0C3.58172 0 0 3.58172 0 8C0 12.4183 3.58172 16 8 16C12.4183 16 16 12.4183 16 8C16 3.58172 12.4183 0 8 0Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

GlobeIcon.displayName = "GlobeIcon";
