/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type GlobeIconProps = SvgIconNoChildrenProps;

export const GlobeIcon = forwardRef<SVGSVGElement, GlobeIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M1.018 7.5a7.004 7.004 0 0 1 5.63-6.37C5.214 2.839 4.525 5.153 4.5 7.5H1.018ZM8 1.16C6.364 2.662 5.53 5.006 5.5 7.5h5c-.028-2.493-.864-4.837-2.5-6.34Zm2.468 7.34H5.532c.171 2.296 1.015 4.573 2.468 6.26 1.453-1.687 2.297-3.964 2.468-6.26Zm-1.3 6.403c1.372-1.82 2.146-4.118 2.303-6.403h3.511a7.003 7.003 0 0 1-5.813 6.403ZM11.5 7.5c-.025-2.348-.713-4.662-2.147-6.37a7.004 7.004 0 0 1 5.63 6.37H11.5Zm-10.482 1H4.53c.157 2.285.93 4.583 2.302 6.403A7.003 7.003 0 0 1 1.018 8.5ZM8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

GlobeIcon.displayName = "GlobeIcon";
