/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type GlobeIconProps = SvgIconNoChildrenProps;

export const GlobeIcon = forwardRef<SVGSVGElement, GlobeIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M4.51 8.5H1.019a7.003 7.003 0 0 0 5.779 6.397A11.445 11.445 0 0 1 4.511 8.5Zm1.002 0h4.976A10.453 10.453 0 0 1 8 14.801 10.453 10.453 0 0 1 5.512 8.5Zm4.976-1H5.512C5.624 5.1 6.542 2.913 8 1.199A10.453 10.453 0 0 1 10.488 7.5Zm1.001 1a11.446 11.446 0 0 1-2.286 6.397 7.003 7.003 0 0 0 5.78-6.397h-3.494Zm3.493-1H11.49a11.445 11.445 0 0 0-2.286-6.397 7.003 7.003 0 0 1 5.78 6.397Zm-10.471 0H1.018a7.003 7.003 0 0 1 5.779-6.397A11.445 11.445 0 0 0 4.511 7.5ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

GlobeIcon.displayName = "GlobeIcon";
