/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type GridIconProps = SvgIconNoChildrenProps;

export const GridIcon = forwardRef<SVGSVGElement, GridIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M1.00003 1H1.50003H4.50003H5.00003V1.5V4.5V5H4.50003H1.50003H1.00003V4.5V1.5V1ZM2.00003 2V4H4.00003V2H2.00003ZM6.00002 1H6.50002H9.50002H10V1.5V4.5V5H9.50002H6.50002H6.00002V4.5V1.5V1ZM7.00002 2V4H9.00002V2H7.00002ZM11.5 1H11V1.5V4.5V5H11.5H14.5H15V4.5V1.5V1H14.5H11.5ZM12 4V2H14V4H12ZM1.00003 6H1.50003H4.50003H5.00003V6.5V9.5V10H4.50003H1.50003H1.00003V9.5V6.5V6ZM2.00003 7V9H4.00003V7H2.00003ZM6.50003 6H6.00003V6.5V9.5V10H6.50003H9.50003H10V9.5V6.5V6H9.50003H6.50003ZM7.00003 9V7H9.00003V9H7.00003ZM11 6H11.5H14.5H15V6.5V9.5V10H14.5H11.5H11V9.5V6.5V6ZM12 7V9H14V7H12ZM1.50003 11H1.00003V11.5V14.5V15H1.50003H4.50003H5.00003V14.5V11.5V11H4.50003H1.50003ZM2.00003 14V12H4.00003V14H2.00003ZM6.00003 11H6.50003H9.50003H10V11.5V14.5V15H9.50003H6.50003H6.00003V14.5V11.5V11ZM7.00003 12V14H9.00003V12H7.00003ZM11.5 11H11V11.5V14.5V15H11.5H14.5H15V14.5V11.5V11H14.5H11.5ZM12 14V12H14V14H12Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

GridIcon.displayName = "GridIcon";
