/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type GridIconProps = SvgIconNoChildrenProps;

export const GridIcon = forwardRef<SVGSVGElement, GridIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M1 1h4v4H1V1Zm1 1v2h2V2H2Zm4-1h4v4H6V1Zm1 1v2h2V2H7Zm4.5-1H11v4h4V1h-3.5Zm.5 3V2h2v2h-2ZM1 6h4v4H1V6Zm1 1v2h2V7H2Zm4.5-1H6v4h4V6H6.5ZM7 9V7h2v2H7Zm4-3h4v4h-4V6Zm1 1v2h2V7h-2ZM1.5 11H1v4h4v-4H1.5Zm.5 3v-2h2v2H2Zm4-3h4v4H6v-4Zm1 1v2h2v-2H7Zm4.5-1H11v4h4v-4h-3.5Zm.5 3v-2h2v2h-2Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

GridIcon.displayName = "GridIcon";
