/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type HomeIconProps = SvgIconNoChildrenProps;

export const HomeIcon = forwardRef<SVGSVGElement, HomeIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="m1 6.56.324-.297 6-5.5L8 .143l.676.62 6 5.5.324.297V12.525c0 .21 0 .415-.012.589a2.03 2.03 0 0 1-.14.65 2 2 0 0 1-1.083 1.082 2.03 2.03 0 0 1-.65.14 9.071 9.071 0 0 1-.588.012H10V10a2 2 0 1 0-4 0v4.998H3.474c-.21 0-.415 0-.59-.011a2.03 2.03 0 0 1-.65-.14 2 2 0 0 1-1.082-1.083 2.029 2.029 0 0 1-.14-.65C1 12.94 1 12.735 1 12.525V6.56ZM8 1.5 2 7v5.498c0 .466 0 .7.076.883a1 1 0 0 0 .541.541c.184.076.417.076.883.076H5V10a3 3 0 0 1 6 0v3.998h1.5c.466 0 .699 0 .883-.076a1 1 0 0 0 .54-.54c.077-.184.077-.418.077-.883V7L8 1.5Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

HomeIcon.displayName = "HomeIcon";
