/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type InformationCircleIconProps = SvgIconNoChildrenProps;

export const InformationCircleIcon = forwardRef<
  SVGSVGElement,
  InformationCircleIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M1 8a7 7 0 1 1 14 0A7 7 0 0 1 1 8Zm7-8a8 8 0 1 0 0 16A8 8 0 0 0 8 0Zm0 5.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM8 7a.5.5 0 0 1 .5.5V12h-1V7.5A.5.5 0 0 1 8 7Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

InformationCircleIcon.displayName = "InformationCircleIcon";
