/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type LinkIconProps = SvgIconNoChildrenProps;

export const LinkIcon = forwardRef<SVGSVGElement, LinkIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M10.0879 1.0141C11.4401 -0.338034 13.6323 -0.338035 14.9845 1.0141C16.3366 2.36624 16.3366 4.55849 14.9845 5.91063L11.8438 9.05132L11.785 9.1101C11.2168 9.67844 10.8636 10.0318 10.4869 10.2559C9.38406 10.9121 8.01049 10.9121 6.90761 10.2559C6.53098 10.0318 6.17771 9.67844 5.60955 9.1101L5.55078 9.05133L6.25789 8.34422C6.90396 8.9903 7.16398 9.24483 7.41894 9.39653C8.20672 9.86526 9.18784 9.86526 9.97561 9.39653C10.2306 9.24483 10.4906 8.9903 11.1367 8.34422L14.2774 5.20352C15.239 4.24191 15.239 2.68282 14.2774 1.72121C13.3158 0.759597 11.7567 0.759597 10.7951 1.72121L8.87769 3.63858C8.43113 3.55036 7.9742 3.53052 7.52298 3.57908L10.0879 1.0141ZM5.20352 14.2825L7.82186 11.6642C8.26794 11.7527 8.72441 11.773 9.17525 11.725L5.91062 14.9896C4.55848 16.3418 2.36624 16.3418 1.0141 14.9896C-0.338034 13.6375 -0.338034 11.4452 1.0141 10.0931L4.85576 6.25144L4.91453 6.19266C5.48269 5.62433 5.83597 5.27094 6.21259 5.04685C7.31547 4.39063 8.68904 4.39063 9.79193 5.04685C10.1686 5.27094 10.5218 5.62433 11.09 6.19266L11.1488 6.25144L10.4416 6.95855C9.79557 6.31247 9.53556 6.05794 9.28059 5.90623C8.49282 5.43751 7.5117 5.43751 6.72393 5.90623C6.46896 6.05794 6.20895 6.31247 5.56287 6.95854L1.72121 10.8002C0.759596 11.7618 0.759596 13.3209 1.72121 14.2825C2.68282 15.2441 4.2419 15.2441 5.20352 14.2825Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

LinkIcon.displayName = "LinkIcon";
