/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type LinkExternalIconProps = SvgIconNoChildrenProps;

export const LinkExternalIcon = forwardRef<
  SVGSVGElement,
  LinkExternalIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M7 2h6.293l-8.147 8.146.708.708L14 2.707V8h1V1.504c0-.005 0-.019-.002-.035A.51.51 0 0 0 14.496 1H7v1Zm4 12V7.132l1-1.016V15H1V4h8.885L8.869 5H2v9h9Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

LinkExternalIcon.displayName = "LinkExternalIcon";
