/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type LinkIconProps = SvgIconNoChildrenProps;

export const LinkIcon = forwardRef<SVGSVGElement, LinkIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M10.088 1.014a3.462 3.462 0 0 1 4.897 4.897l-3.141 3.14-.059.06c-.568.567-.921.92-1.298 1.145a3.5 3.5 0 0 1-3.58 0c-.376-.224-.73-.578-1.297-1.146l-.06-.059.708-.707c.646.646.906.9 1.16 1.053a2.5 2.5 0 0 0 2.558 0c.255-.152.515-.407 1.16-1.053l3.141-3.14a2.462 2.462 0 0 0-3.482-3.483L8.878 3.64a4.504 4.504 0 0 0-1.355-.06l2.565-2.565ZM5.204 14.282l2.618-2.618c.446.089.902.109 1.353.061L5.911 14.99a3.462 3.462 0 1 1-4.897-4.897l3.842-3.842.059-.058c.568-.569.921-.922 1.298-1.146a3.5 3.5 0 0 1 3.579 0c.377.224.73.577 1.298 1.146l.059.058-.707.708c-.646-.647-.906-.901-1.161-1.053a2.5 2.5 0 0 0-2.557 0c-.255.152-.515.406-1.161 1.053L1.72 10.8a2.462 2.462 0 1 0 3.483 3.482Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

LinkIcon.displayName = "LinkIcon";
