/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ListIconProps = SvgIconNoChildrenProps;

export const ListIcon = forwardRef<SVGSVGElement, ListIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M0.5 2H0V2.5V4.5V5H0.5H2.5H3V4.5V2.5V2H2.5H0.5ZM1 4V3H2V4H1ZM0.5 6.5H0V7V9V9.5H0.5H2.5H3V9V7V6.5H2.5H0.5ZM1 8.5V7.5H2V8.5H1ZM0 11H0.5H2.5H3V11.5V13.5V14H2.5H0.5H0V13.5V11.5V11ZM1 12V13H2V12H1ZM4 4H16V3H4V4ZM16 13H4V12H16V13ZM4 8.5H16V7.5H4V8.5Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ListIcon.displayName = "ListIcon";
