/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ListIconProps = SvgIconNoChildrenProps;

export const ListIcon = forwardRef<SVGSVGElement, ListIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M.5 2H0v3h3V2H.5ZM1 4V3h1v1H1ZM.5 6.5H0v3h3v-3H.5Zm.5 2v-1h1v1H1ZM0 11h3v3H0v-3Zm1 1v1h1v-1H1Zm3-8h12V3H4v1Zm12 9H4v-1h12v1ZM4 8.5h12v-1H4v1Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

ListIcon.displayName = "ListIcon";
