/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type LockIconProps = SvgIconNoChildrenProps;

export const LockIcon = forwardRef<SVGSVGElement, LockIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M5 11h14v8a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-8Zm12-5v3h4v10a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9h4V6a5 5 0 0 1 10 0Zm-2 0v3H9V6a3 3 0 1 1 6 0Zm-3 11.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

LockIcon.displayName = "LockIcon";
