/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type NotificationIconProps = SvgIconNoChildrenProps;

export const NotificationIcon = forwardRef<
  SVGSVGElement,
  NotificationIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="m15.125 12 .375 1H11a3 3 0 1 1-6 0H.5l.375-1 .736-1.963a8.88 8.88 0 0 0 .511-2.138l.326-2.93a5.586 5.586 0 0 1 11.104 0l.326 2.93a8.88 8.88 0 0 0 .51 2.138L15.126 12ZM6 13a2 2 0 1 0 4 0H6Zm-1-1H1.943l.605-1.612a9.88 9.88 0 0 0 .568-2.378l.326-2.93a4.586 4.586 0 0 1 9.116 0l.326 2.93a9.88 9.88 0 0 0 .569 2.378L14.056 12H5Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

NotificationIcon.displayName = "NotificationIcon";
