/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type NotificationIconProps = SvgIconNoChildrenProps;

export const NotificationIcon = forwardRef<
  SVGSVGElement,
  NotificationIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M7.88456 0C5.15797 0 2.98886 2.17591 2.69571 4.83279C2.38596 7.64019 1.85808 10.2622 1.20357 12.3505L1 13H1.68069H4.99609C4.99609 14.6761 6.31995 16 7.99609 16C9.67224 16 10.9961 14.6761 10.9961 13H14.3176H14.9983L14.7947 12.3505C14.1402 10.2622 13.6123 7.64019 13.3026 4.83279C13.0094 2.17591 10.8403 0 8.11372 0H7.88456ZM9.99609 13H5.99609C5.99609 14.1239 6.87224 15 7.99609 15C9.11995 15 9.99609 14.1239 9.99609 13ZM3.68968 4.94246C3.93289 2.7382 5.7205 1 7.88456 1H8.11372C10.2778 1 12.0654 2.73819 12.3086 4.94246C12.593 7.52028 13.0594 9.95965 13.6456 12H2.35269C2.93883 9.95965 3.40526 7.52028 3.68968 4.94246Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

NotificationIcon.displayName = "NotificationIcon";
