/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type NotificationIconProps = SvgIconNoChildrenProps;

export const NotificationIcon = forwardRef<
  SVGSVGElement,
  NotificationIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M7.885 0c-2.727 0-4.896 2.176-5.19 4.833-.309 2.807-.837 5.43-1.491 7.518L1 13h3.996c0 1.676 1.324 3 3 3s3-1.324 3-3h4.002l-.203-.65c-.655-2.088-1.183-4.71-1.492-7.517C13.009 2.176 10.84 0 8.113 0h-.228Zm2.111 13h-4c0 1.124.876 2 2 2s2-.876 2-2ZM3.69 4.942C3.933 2.738 5.72 1 7.885 1h.229c2.164 0 3.951 1.738 4.195 3.942.284 2.578.75 5.018 1.337 7.058H2.353c.586-2.04 1.052-4.48 1.337-7.058Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

NotificationIcon.displayName = "NotificationIcon";
