/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type QuestionCircleFilledIconProps = SvgIconNoChildrenProps;

export const QuestionCircleFilledIcon = forwardRef<
  SVGSVGElement,
  QuestionCircleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM8 5c-.542 0-1.18.387-1.646.854l-.708-.708C6.18 4.613 7.061 4 8 4a2.5 2.5 0 0 1 2.5 2.5c0 .742-.352 1.238-.778 1.649-.178.172-.381.34-.58.505l-.088.073a10.09 10.09 0 0 0-.7.627.5.5 0 1 1-.708-.708c.268-.267.532-.491.769-.688l.09-.075c.203-.168.374-.31.523-.454.324-.313.472-.566.472-.929A1.5 1.5 0 0 0 8 5Zm0 7a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

QuestionCircleFilledIcon.displayName = "QuestionCircleFilledIcon";
