/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type QuestionCircleIconProps = SvgIconNoChildrenProps;

export const QuestionCircleIcon = forwardRef<
  SVGSVGElement,
  QuestionCircleIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14Zm8-7A8 8 0 1 1 0 8a8 8 0 0 1 16 0Zm-8 4a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM6.354 5.854C6.82 5.387 7.458 5 8 5a1.5 1.5 0 0 1 1.5 1.5c0 .363-.148.616-.472.93-.15.143-.32.285-.523.453l-.09.075c-.237.197-.501.421-.769.688a.5.5 0 1 0 .708.708c.232-.233.468-.433.7-.627l.088-.073c.199-.165.402-.333.58-.505.426-.41.778-.907.778-1.649A2.5 2.5 0 0 0 8 4c-.939 0-1.82.613-2.354 1.146l.708.708Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

QuestionCircleIcon.displayName = "QuestionCircleIcon";
