/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type QuestionCircleFilledIconProps = SvgIconNoChildrenProps;

export const QuestionCircleFilledIcon = forwardRef<
  SVGSVGElement,
  QuestionCircleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM8 5c-.824 0-1.5.676-1.5 1.5h-1C5.5 5.124 6.624 4 8 4s2.5 1.124 2.5 2.5c0 1.004-.519 1.758-1.352 2.234l-.012.007-.012.006a1.925 1.925 0 0 0-.649.553c-.182.243-.275.49-.275.7h-1c0-.49.207-.943.475-1.3.266-.355.62-.653.988-.84.56-.324.837-.768.837-1.36C9.5 5.676 8.824 5 8 5Zm-.25 8.5a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
          clipRule="evenodd"
        />
      </>
    </SvgIcon>
  );
});

QuestionCircleFilledIcon.displayName = "QuestionCircleFilledIcon";
