/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type RefreshIconProps = SvgIconNoChildrenProps;

export const RefreshIcon = forwardRef<SVGSVGElement, RefreshIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M8 1C4.13401 1 1 4.13401 1 8H0C0 3.58172 3.58172 0 8 0C11.0127 0 13.6356 1.6652 15 4.12425V1.5H16V5.5C16 5.77614 15.7761 6 15.5 6H11.5V5H14.3265C13.2028 2.63444 10.7917 1 8 1ZM8 15C11.866 15 15 11.866 15 8H16C16 12.4183 12.4183 16 8 16C4.98729 16 2.36445 14.3349 1 11.8757V14.5H0V10.5C0 10.2239 0.223858 10 0.5 10H4.5V11H1.67348C2.79718 13.3655 5.20825 15 8 15Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

RefreshIcon.displayName = "RefreshIcon";
