/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ResetIconProps = SvgIconNoChildrenProps;

export const ResetIcon = forwardRef<SVGSVGElement, ResetIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M1.995 8.12c0-3.325 2.698-6.12 6-6.12 2.163 0 4.074 1.234 5.131 3H11.03v1h3.467a.5.5 0 0 0 .5-.5V2h-1v2.507C12.776 2.457 10.554 1 7.996 1c-3.878 0-7 3.266-7 7.12 0 3.879 3.146 6.88 7 6.88a7 7 0 0 0 7-7h-1a6 6 0 0 1-6 6c-3.327 0-6-2.578-6-5.88Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

ResetIcon.displayName = "ResetIcon";
