/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ResetIconProps = SvgIconNoChildrenProps;

export const ResetIcon = forwardRef<SVGSVGElement, ResetIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M1 8C1 4.13401 4.13401 1 8 1C10.7917 1 13.2027 2.6344 14.3265 5H11.5V6H15.5C15.7761 6 16 5.77614 16 5.5V1.5H15V4.12425C13.6356 1.66522 11.0128 0 8 0C3.58172 0 0 3.58172 0 8C0 12.4183 3.58172 16 8 16C12.4183 16 16 12.4183 16 8H15C15 11.866 11.866 15 8 15C4.13401 15 1 11.866 1 8Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ResetIcon.displayName = "ResetIcon";
