/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type SearchIconProps = SvgIconNoChildrenProps;

export const SearchIcon = forwardRef<SVGSVGElement, SearchIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M12 7A5 5 0 1 1 2 7a5 5 0 0 1 10 0Zm-2.674 5.533a6 6 0 1 1 3.207-3.207l2.57 2.57a2.268 2.268 0 0 1-3.207 3.208l-2.57-2.571Zm.925-.49 2.353 2.353a1.268 1.268 0 1 0 1.792-1.792l-2.352-2.353a6.03 6.03 0 0 1-1.793 1.793Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

SearchIcon.displayName = "SearchIcon";
