/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type SettingsIconProps = SvgIconNoChildrenProps;

export const SettingsIcon = forwardRef<SVGSVGElement, SettingsIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            d="m12.792 8.315-1.133-.863a3.9 3.9 0 0 0 0-.906l1.134-.862a.531.531 0 0 0 .134-.69l-1.178-1.983a.564.564 0 0 0-.682-.24l-1.335.524c-.25-.178-.52-.33-.802-.454L8.725 1.46A.541.541 0 0 0 8.18 1H5.818a.54.54 0 0 0-.542.456l-.205 1.385c-.282.126-.55.278-.801.454L2.93 2.771a.553.553 0 0 0-.676.234l-1.18 1.987a.528.528 0 0 0 .135.693l1.132.862a3.872 3.872 0 0 0 0 .906l-1.134.863a.531.531 0 0 0-.134.69l1.178 1.983a.564.564 0 0 0 .681.24l1.335-.523c.251.177.52.329.803.454l.205 1.38a.54.54 0 0 0 .542.46H8.18a.54.54 0 0 0 .544-.456l.205-1.385c.282-.126.55-.278.801-.454l1.34.524a.553.553 0 0 0 .676-.234L12.93 9a.53.53 0 0 0-.137-.685ZM6.999 9.5C5.581 9.5 4.432 8.38 4.432 7s1.15-2.5 2.567-2.5c1.418 0 2.567 1.12 2.567 2.5C9.565 8.38 8.416 9.498 7 9.5Z"
          />
        </>
      </SvgIcon>
    );
  }
);

SettingsIcon.displayName = "SettingsIcon";
