/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type SyncIconProps = SvgIconNoChildrenProps;

export const SyncIcon = forwardRef<SVGSVGElement, SyncIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M14.297 3.002 12.007.711l.706-.707 3.134 3.133.008.008.024.027a.51.51 0 0 1 0 .66l-.024.027-.008.008L12.713 7l-.707-.707 2.291-2.291H3.898c-.428 0-.72 0-.944.019-.22.018-.332.05-.41.09a1 1 0 0 0-.437.437c-.04.078-.072.19-.09.41-.018.225-.019.516-.019.944v2.977l-1 1V5.882c0-.403 0-.735.022-1.006.023-.281.073-.54.196-.782a2 2 0 0 1 .874-.874c.243-.124.501-.173.782-.196.27-.022.603-.022 1.006-.022h10.42Zm.842.842Zm0-.683a.04.04 0 0 1 0-.001Zm-1.14 6.94V7.128l1-1v3.995c0 .403 0 .735-.022 1.005-.023.282-.072.54-.195.783a2 2 0 0 1-.874.874c-.243.123-.502.173-.782.195-.271.023-.603.023-1.006.023H1.703l2.29 2.29-.706.708-3.133-3.133-.009-.009a.51.51 0 0 1 0-.713l.009-.008 3.133-3.133.707.707L1.704 12H12.1c.428 0 .719 0 .944-.018.22-.018.331-.05.41-.09a1 1 0 0 0 .437-.437c.04-.079.072-.19.09-.41.018-.225.019-.516.019-.944ZM.862 12.16a.083.083 0 0 1 0 .002v-.002Zm0 .684a.121.121 0 0 1 0 .001v-.001Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

SyncIcon.displayName = "SyncIcon";
