/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type UploadIconProps = SvgIconNoChildrenProps;

export const UploadIcon = forwardRef<SVGSVGElement, UploadIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M8.36858 0.162138C8.27387 0.0588232 8.14015 0 8 0C7.85985 0 7.72613 0.0588232 7.63142 0.162138L2.13142 6.16214L2.86858 6.83786L7.5 1.7854V13H8.5V1.7854L13.1314 6.83786L13.8686 6.16214L8.36858 0.162138ZM1 13.1V11H2V13.1C2 13.5283 2.00039 13.8194 2.01878 14.0445C2.03669 14.2637 2.06915 14.3758 2.10899 14.454C2.20487 14.6422 2.35785 14.7951 2.54601 14.891C2.62421 14.9309 2.73631 14.9633 2.95552 14.9812C3.18056 14.9996 3.47171 15 3.9 15H12.1C12.5283 15 12.8194 14.9996 13.0445 14.9812C13.2637 14.9633 13.3758 14.9309 13.454 14.891C13.6422 14.7951 13.7951 14.6422 13.891 14.454C13.9309 14.3758 13.9633 14.2637 13.9812 14.0445C13.9996 13.8194 14 13.5283 14 13.1V11H15V13.1V13.1207C15 13.5231 15 13.8553 14.9779 14.1259C14.9549 14.407 14.9057 14.6653 14.782 14.908C14.5903 15.2843 14.2843 15.5903 13.908 15.782C13.6653 15.9057 13.407 15.9549 13.1259 15.9779C12.8553 16 12.5231 16 12.1206 16H12.1H3.9H3.87936C3.47687 16 3.14469 16 2.87409 15.9779C2.59304 15.9549 2.33469 15.9057 2.09202 15.782C1.7157 15.5903 1.40973 15.2843 1.21799 14.908C1.09434 14.6653 1.04506 14.407 1.0221 14.1259C0.999989 13.8553 0.999994 13.5231 1 13.1207V13.1206V13.1Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

UploadIcon.displayName = "UploadIcon";
