/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type UserIconProps = SvgIconNoChildrenProps;

export const UserIcon = forwardRef<SVGSVGElement, UserIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M8 0a3 3 0 0 0-3 3v2a3 3 0 0 0 6 0V3a3 3 0 0 0-3-3ZM6 3a2 2 0 1 1 4 0v2a2 2 0 1 1-4 0V3Zm-2.363 7.712A1 1 0 0 1 4.595 10H11.4a1 1 0 0 1 .958.712L13.65 15H2.346l1.291-4.288ZM4.595 9a2 2 0 0 0-1.915 1.423l-1.486 4.933L1 16h13.996l-.194-.644-1.486-4.933A2 2 0 0 0 11.401 9H4.595Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

UserIcon.displayName = "UserIcon";
