/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type UserGroupIconProps = SvgIconNoChildrenProps;

export const UserGroupIcon = forwardRef<SVGSVGElement, UserGroupIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M10.847 0a2.25 2.25 0 0 0-2.25 2.25v1.5a2.25 2.25 0 1 0 4.5 0v-1.5A2.25 2.25 0 0 0 10.847 0Zm-1.25 2.25a1.25 1.25 0 1 1 2.5 0v1.5a1.25 1.25 0 1 1-2.5 0v-1.5ZM11.679 8c.66 0 .855.008 1.01.069a1 1 0 0 1 .4.286c.106.127.176.308.389.933L14.4 12H8.436l-.011-.034-.029-.083c-.17-.504-.299-.882-.543-1.172a1.915 1.915 0 0 0-.041-.047l.492-1.396c.218-.616.29-.794.396-.919a1 1 0 0 1 .398-.282c.153-.059.345-.067.998-.067h1.583Zm-4.73 2.101.412-1.166.03-.083c.174-.495.305-.869.55-1.154a2 2 0 0 1 .796-.563C9.087 6.999 9.483 7 10.01 7h1.759c.531 0 .931 0 1.284.137a2 2 0 0 1 .8.574c.245.29.374.668.544 1.172l.029.083 1.146 3.373.225.661h-7.02l.795 2.339.225.661H0l.225-.661 1.146-3.373.029-.083c.17-.504.299-.882.544-1.172a2 2 0 0 1 .8-.574C3.097 10 3.497 10 4.029 10h1.739c.48 0 .853 0 1.182.101ZM2.598 5.25a2.25 2.25 0 0 1 4.5 0v1.5a2.25 2.25 0 0 1-4.5 0v-1.5ZM4.847 4c-.69 0-1.25.56-1.25 1.25v1.5a1.25 1.25 0 1 0 2.5 0v-1.5c0-.69-.56-1.25-1.25-1.25Zm-1.739 7.069c.155-.06.348-.069 1.009-.069h1.562c.66 0 .855.008 1.01.069a1 1 0 0 1 .4.286c.106.127.176.308.389.933L8.4 15H1.396l.922-2.712c.213-.625.283-.806.39-.933a1 1 0 0 1 .4-.286Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

UserGroupIcon.displayName = "UserGroupIcon";
