/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type UserIconProps = SvgIconNoChildrenProps;

export const UserIcon = forwardRef<SVGSVGElement, UserIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M10 3v2a2 2 0 1 1-4 0V3a2 2 0 1 1 4 0ZM5 3a3 3 0 0 1 6 0v2a3 3 0 0 1-6 0V3Zm-.87 7.074c.138-.056.329-.074 1.284-.074h5.172c.955 0 1.146.018 1.284.074.16.066.3.172.408.308.091.117.161.296.424 1.214L13.674 15H2.326l.972-3.404c.263-.918.333-1.097.424-1.214.107-.136.248-.242.408-.308Zm9.533 1.247L14.714 15 15 16H1l.286-1 1.05-3.68c.239-.831.357-1.247.6-1.556a2 2 0 0 1 .816-.616C4.116 9 4.55 9 5.414 9h5.172c.865 0 1.298 0 1.662.148a2 2 0 0 1 .816.616c.243.309.361.725.6 1.557Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

UserIcon.displayName = "UserIcon";
