/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type UserGroupIconProps = SvgIconNoChildrenProps;

export const UserGroupIcon = forwardRef<SVGSVGElement, UserGroupIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill="currentColor"
            fillRule="evenodd"
            d="M12 4V3a1 1 0 1 0-2 0v1a1 1 0 1 0 2 0Zm-1-3a2 2 0 0 0-2 2v1a2 2 0 1 0 4 0V3a2 2 0 0 0-2-2Zm2.45 8.71a15.26 15.26 0 0 0-.239-.97c-.064-.208-.11-.286-.14-.328l.81-.588c.24.331.342.775.545 1.663L14.77 11 15 12H8.313c.035.146.072.307.113.487L8.77 14 9 15H1l.229-1 .345-1.513c.203-.888.305-1.332.546-1.663a2 2 0 0 1 .831-.663C3.328 10 3.783 10 4.694 10h.612c.91 0 1.366 0 1.743.16a2 2 0 0 1 .33.18l.195-.853c.203-.888.305-1.332.546-1.663a2 2 0 0 1 .831-.663C9.328 7 9.783 7 10.694 7h.612c.91 0 1.366 0 1.743.16a2 2 0 0 1 .832.664l-.81.588a1 1 0 0 0-.415-.332c-.048-.02-.134-.047-.351-.063A15.32 15.32 0 0 0 11.306 8h-.612c-.47 0-.769 0-.999.017-.217.016-.303.043-.35.063a1 1 0 0 0-.417.332c-.03.042-.075.12-.14.328-.067.22-.134.512-.239.97L8.254 11h5.492l-.278-1.214-.017-.076ZM6 7V6a1 1 0 0 0-2 0v1a1 1 0 0 0 2 0ZM5 4a2 2 0 0 0-2 2v1a2 2 0 1 0 4 0V6a2 2 0 0 0-2-2Zm.306 7h-.612c-.47 0-.769 0-.999.017-.217.016-.303.043-.35.063a1 1 0 0 0-.417.332c-.03.042-.075.12-.14.328-.067.22-.134.512-.239.97L2.254 14h5.492l-.295-1.29c-.105-.458-.172-.75-.24-.97-.064-.208-.11-.286-.14-.328a1 1 0 0 0-.415-.332c-.048-.02-.134-.047-.351-.063-.23-.016-.53-.017-.999-.017Z"
            clipRule="evenodd"
          />
        </>
      </SvgIcon>
    );
  }
);

UserGroupIcon.displayName = "UserGroupIcon";
