/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type UserIconProps = SvgIconNoChildrenProps;

export const UserIcon = forwardRef<SVGSVGElement, UserIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M8 0C6.34315 0 5 1.34315 5 3V5C5 6.65685 6.34315 8 8 8C9.65685 8 11 6.65685 11 5V3C11 1.34315 9.65685 0 8 0ZM6 3C6 1.89543 6.89543 1 8 1C9.10457 1 10 1.89543 10 3V5C10 6.10457 9.10457 7 8 7C6.89543 7 6 6.10457 6 5V3ZM3.63727 10.7116C3.76451 10.2891 4.15358 10 4.59478 10H11.4014C11.8426 10 12.2316 10.2891 12.3589 10.7116L13.6506 15H2.34558L3.63727 10.7116ZM4.59478 9C3.71238 9 2.93425 9.57828 2.67976 10.4232L1.19404 15.3558L1 16H1.67279H14.3234H14.9962L14.8021 15.3558L13.3164 10.4232C13.0619 9.57828 12.2838 9 11.4014 9H4.59478Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

UserIcon.displayName = "UserIcon";
