/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowUpperLeftIconProps = SvgIconNoChildrenProps;

export const ArrowUpperLeftIcon = forwardRef<
  SVGSVGElement,
  ArrowUpperLeftIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M6 7.5V14H8L8 9.41421L16.2929 17.7071L17.7071 16.2929L9.41421 8L14 8V6H7.5C6.67157 6 6 6.67157 6 7.5Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ArrowUpperLeftIcon.displayName = "ArrowUpperLeftIcon";
