/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowLowerRightIconProps = SvgIconNoChildrenProps;

export const ArrowLowerRightIcon = forwardRef<
  SVGSVGElement,
  ArrowLowerRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M16.0711 14.6568L7.70712 6.29288L6.29291 7.70709L14.5858 16L10 16V18H16.5711C17.3995 18 18.0711 17.3284 18.0711 16.5V9.92892L16.0711 9.92892L16.0711 14.6568Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ArrowLowerRightIcon.displayName = "ArrowLowerRightIcon";
