/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowLeftIconProps = SvgIconNoChildrenProps;

export const ArrowLeftIcon = forwardRef<SVGSVGElement, ArrowLeftIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5.64643 13.0607L10.2929 17.7071L11.7071 16.2929L8.4142 13L19 13V11L8.4142 11L11.7071 7.70712L10.2929 6.29291L5.64643 10.9394C5.06065 11.5251 5.06064 12.4749 5.64643 13.0607Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ArrowLeftIcon.displayName = "ArrowLeftIcon";
