/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowLowerLeftIconProps = SvgIconNoChildrenProps;

export const ArrowLowerLeftIcon = forwardRef<
  SVGSVGElement,
  ArrowLowerLeftIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M8 14.5858L16.2929 6.29288L17.7071 7.70709L9.41421 16L14 16V18L7.5 18C6.67157 18 6 17.3284 6 16.5V9.99998H8L8 14.5858Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ArrowLowerLeftIcon.displayName = "ArrowLowerLeftIcon";
