/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowBottomIconProps = SvgIconNoChildrenProps;

export const ArrowBottomIcon = forwardRef<SVGSVGElement, ArrowBottomIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M18 20.0008L6 20.0008L6 22.0008L18 22.0008L18 20.0008ZM17.7071 13.7079L13.0607 18.3544C12.4749 18.9402 11.5251 18.9402 10.9393 18.3544L6.2929 13.7079L7.70711 12.2937L11 15.5866L11 5.0008L13 5.0008L13 15.5866L16.2929 12.2937L17.7071 13.7079Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  },
);

ArrowBottomIcon.displayName = "ArrowBottomIcon";
