/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowUpIconProps = SvgIconNoChildrenProps;

export const ArrowUpIcon = forwardRef<SVGSVGElement, ArrowUpIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M10.9393 5.64643L6.29289 10.2929L7.70711 11.7071L11 8.4142V19H13V8.4142L16.2929 11.7071L17.7071 10.2929L13.0607 5.64643C12.4749 5.06065 11.5251 5.06064 10.9393 5.64643Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ArrowUpIcon.displayName = "ArrowUpIcon";
