/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowDownIconProps = SvgIconNoChildrenProps;

export const ArrowDownIcon = forwardRef<SVGSVGElement, ArrowDownIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M13 15.5858L13 5H11L11 15.5858L7.70711 12.2929L6.29289 13.7071L10.9393 18.3536C11.5251 18.9393 12.4749 18.9393 13.0607 18.3536L17.7071 13.7071L16.2929 12.2929L13 15.5858Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ArrowDownIcon.displayName = "ArrowDownIcon";
