/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowUnsortedIconProps = SvgIconNoChildrenProps;

export const ArrowUnsortedIcon = forwardRef<
  SVGSVGElement,
  ArrowUnsortedIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M17 15.5858L17 5H15L15 15.5858L12.7071 13.2929L11.2929 14.7071L14.9393 18.3535C15.5251 18.9393 16.4749 18.9393 17.0607 18.3535L20.7071 14.7071L19.2929 13.2929L17 15.5858ZM6.93934 5.64645L3.29289 9.29289L4.70711 10.7071L7 8.41422V19H9V8.41422L11.2929 10.7071L12.7071 9.29289L9.06066 5.64645C8.47487 5.06067 7.52513 5.06067 6.93934 5.64645Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ArrowUnsortedIcon.displayName = "ArrowUnsortedIcon";
