/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ArrowUpperRightIconProps = SvgIconNoChildrenProps;

export const ArrowUpperRightIcon = forwardRef<
  SVGSVGElement,
  ArrowUpperRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M18 7.5L18 14H16L16 9.41421L7.70712 17.7071L6.29291 16.2929L14.5858 8L10 8V6H16.5C17.3284 6 18 6.67157 18 7.5Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ArrowUpperRightIcon.displayName = "ArrowUpperRightIcon";
