/*!
 * Copyright (c) 2024-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type AuraWordmarkIconProps = SvgIconNoChildrenProps;

export const AuraWordmarkIcon = forwardRef<
  SVGSVGElement,
  AuraWordmarkIconProps
>((props, ref) => {
  return (
    <SvgIcon
      width="56"
      height="21"
      viewBox="0 0 56 21"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M46.7706 17.7962C44.0858 17.7962 42.1876 15.7083 42.1876 12.9694C42.1876 10.2304 44.0858 8.1426 46.7706 8.1426C49.4553 8.1426 51.2994 10.2304 51.2994 12.9694C51.2994 15.7083 49.4283 17.7962 46.7706 17.7962ZM46.3367 20.6706C48.5062 20.6706 50.3503 19.8298 51.5161 18.0671C51.7328 19.7756 52.9804 20.3992 54.553 20.3992H55.8006V17.6873H55.2583C54.3634 17.6873 54.1467 17.2534 54.1467 16.2501V5.53862H51.2723V7.73529C50.2961 6.18974 48.4521 5.26772 46.3371 5.26772C42.5678 5.26772 39.097 8.4135 39.097 12.9689C39.097 17.5243 42.5673 20.6706 46.3367 20.6706ZM31.5308 16.9554C31.5308 19.3959 33.0492 20.3992 34.8662 20.3992H38.3641V17.6873H35.8153C34.7578 17.6873 34.5406 17.2805 34.5406 16.2501V8.25048H38.3641V5.53862H34.5406V0.548828H31.5308V16.9554ZM17.8365 20.3992H20.8464V14.0268H21.8496L26.9749 20.3992H30.7713L24.2359 12.3183L29.2528 5.5391H25.8632L21.7684 11.2608H20.8464V0.549779H17.8365V20.3992ZM8.07411 5.26772C3.87088 5.26772 0.400024 8.4135 0.400024 12.9689C0.400024 17.5243 3.87088 20.6701 8.07411 20.6701C12.2773 20.6701 15.7482 17.5243 15.7482 12.9689C15.7482 8.4135 12.2773 5.26772 8.07411 5.26772ZM8.07411 17.7962C5.38934 17.7962 3.49113 15.7083 3.49113 12.9694C3.49113 10.2304 5.38934 8.1426 8.07411 8.1426C10.7589 8.1426 12.6571 10.2304 12.6571 12.9694C12.6571 15.7083 10.7589 17.7962 8.07411 17.7962Z"
          fill="black"
        />
      </>
    </SvgIcon>
  );
});

AuraWordmarkIcon.displayName = "AuraWordmarkIcon";
