/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type CalendarIconProps = SvgIconNoChildrenProps;

export const CalendarIcon = forwardRef<SVGSVGElement, CalendarIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M9 1V4H15V1H17V4H21H22V5V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V5V4H3H7V1H9ZM15 6V8H17V6H20V9H4V6H7V8H9V6H15ZM4 11V19C4 19.5523 4.44772 20 5 20H19C19.5523 20 20 19.5523 20 19V11H4Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

CalendarIcon.displayName = "CalendarIcon";
