/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type CheckCircleFilledIconProps = SvgIconNoChildrenProps;

export const CheckCircleFilledIcon = forwardRef<
  SVGSVGElement,
  CheckCircleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M23 12C23 18.0751 18.0752 23 12 23C5.9249 23 1.00003 18.0751 1.00003 12C1.00003 5.92487 5.9249 1 12 1C18.0752 1 23 5.92487 23 12ZM7.9216 11.2071L10.75 14.0356L16.4069 8.3787L17.8211 9.79291L11.8107 15.8033C11.2249 16.3891 10.2752 16.3891 9.68937 15.8033L6.50739 12.6213L7.9216 11.2071Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

CheckCircleFilledIcon.displayName = "CheckCircleFilledIcon";
