/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ChevronRightIconProps = SvgIconNoChildrenProps;

export const ChevronRightIcon = forwardRef<
  SVGSVGElement,
  ChevronRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M16.7071 12.7071L10.7071 18.7071L9.29289 17.2929L14.5858 12L9.29289 6.70712L10.7071 5.29291L16.7071 11.2929C17.0976 11.6834 17.0976 12.3166 16.7071 12.7071Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ChevronRightIcon.displayName = "ChevronRightIcon";
