/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ChevronUpIconProps = SvgIconNoChildrenProps;

export const ChevronUpIcon = forwardRef<SVGSVGElement, ChevronUpIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M13.1314 8.71716L18.7071 14.2929L17.2929 15.7071L12 10.4142L6.70711 15.7071L5.29289 14.2929L10.8686 8.71716C11.4935 8.09233 12.5065 8.09233 13.1314 8.71716Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ChevronUpIcon.displayName = "ChevronUpIcon";
