/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ChevronDownIconProps = SvgIconNoChildrenProps;

export const ChevronDownIcon = forwardRef<SVGSVGElement, ChevronDownIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M10.9393 16.3536L5.29289 10.7071L6.70711 9.29291L12 14.5858L17.2929 9.29291L18.7071 10.7071L13.0607 16.3536C12.4749 16.9394 11.5251 16.9394 10.9393 16.3536Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ChevronDownIcon.displayName = "ChevronDownIcon";
