/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type CloseIconProps = SvgIconNoChildrenProps;

export const CloseIcon = forwardRef<SVGSVGElement, CloseIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M10.5858 12L6.29289 16.2929L7.70711 17.7071L12 13.4142L16.2929 17.7071L17.7071 16.2929L13.4142 12L17.7071 7.70712L16.2929 6.29291L12 10.5858L7.70711 6.29291L6.29289 7.70712L10.5858 12Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

CloseIcon.displayName = "CloseIcon";
