/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type CloseCircleFilledIconProps = SvgIconNoChildrenProps;

export const CloseCircleFilledIcon = forwardRef<
  SVGSVGElement,
  CloseCircleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M23 12C23 18.0751 18.0752 23 12 23C5.9249 23 1.00003 18.0751 1.00003 12C1.00003 5.92487 5.9249 1 12 1C18.0752 1 23 5.92487 23 12ZM7.05023 15.5355L10.5857 12L7.0502 8.46445L8.46442 7.05024L12 10.5858L15.5355 7.05023L16.9497 8.46445L13.4142 12L16.9497 15.5355L15.5355 16.9497L12 13.4142L8.46444 16.9497L7.05023 15.5355Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

CloseCircleFilledIcon.displayName = "CloseCircleFilledIcon";
