/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type CollapseRightIconProps = SvgIconNoChildrenProps;

export const CollapseRightIcon = forwardRef<
  SVGSVGElement,
  CollapseRightIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M22 22H20V2H22V22ZM14.5858 13H1V11H14.5858L9.29289 5.70711L10.7071 4.29289L17.1414 10.7272L17.1578 10.7436C17.242 10.8278 17.3427 10.9283 17.424 11.0242C17.5183 11.1352 17.6439 11.3038 17.7195 11.5365C17.8174 11.8377 17.8174 12.1623 17.7195 12.4635C17.6439 12.6962 17.5183 12.8648 17.424 12.9758C17.3427 13.0717 17.2421 13.1722 17.1578 13.2564L17.1578 13.2565L17.1414 13.2728L10.7071 19.7071L9.29289 18.2929L14.5858 13Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

CollapseRightIcon.displayName = "CollapseRightIcon";
