/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type CopyIconProps = SvgIconNoChildrenProps;

export const CopyIcon = forwardRef<SVGSVGElement, CopyIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M3.0625 2.125H2.0625V3.125V15C2.0625 16.6569 3.40565 18 5.0625 18H17H18V17V5.125C18 3.46815 16.6569 2.125 15 2.125H3.0625ZM4.0625 15V4.125H15C15.5523 4.125 16 4.57272 16 5.125V16H5.0625C4.51022 16 4.0625 15.5523 4.0625 15ZM20 7V19C20 19.5523 19.5523 20 19 20H6V22H19C20.6569 22 22 20.6569 22 19V7H20Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

CopyIcon.displayName = "CopyIcon";
