/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type DangerDiamondIconProps = SvgIconNoChildrenProps;

export const DangerDiamondIcon = forwardRef<
  SVGSVGElement,
  DangerDiamondIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M14.1213 1.70711C12.9497 0.535538 11.0503 0.535536 9.87868 1.70711L1.70712 9.87867C0.535548 11.0502 0.535549 12.9497 1.70712 14.1213L9.87871 22.2929C11.0503 23.4645 12.9498 23.4645 14.1213 22.2929L22.2929 14.1213C23.4645 12.9498 23.4645 11.0503 22.2929 9.8787L14.1213 1.70711ZM11.2929 3.12132C11.6834 2.7308 12.3166 2.7308 12.7071 3.12132L20.8787 11.2929C21.2692 11.6834 21.2692 12.3166 20.8787 12.7071L12.7071 20.8787C12.3166 21.2692 11.6834 21.2692 11.2929 20.8787L3.12134 12.7071C2.73081 12.3166 2.73081 11.6834 3.12133 11.2929L11.2929 3.12132ZM12 13C11.4477 13 11 12.5523 11 12L11 7L13 7L13 12C13 12.5523 12.5523 13 12 13ZM12 14.75C11.3096 14.75 10.75 15.3096 10.75 16C10.75 16.6904 11.3096 17.25 12 17.25C12.6903 17.25 13.25 16.6904 13.25 16C13.25 15.3096 12.6903 14.75 12 14.75Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

DangerDiamondIcon.displayName = "DangerDiamondIcon";
