/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type DangerDiamondFilledIconProps = SvgIconNoChildrenProps;

export const DangerDiamondFilledIcon = forwardRef<
  SVGSVGElement,
  DangerDiamondFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M9.87873 1.70711C11.0503 0.535536 12.9498 0.535538 14.1214 1.70711L22.293 9.8787C23.4645 11.0503 23.4645 12.9498 22.293 14.1213L14.1214 22.2929C12.9498 23.4645 11.0503 23.4645 9.87876 22.2929L1.70717 14.1213C0.535598 12.9497 0.535598 11.0502 1.70717 9.87867L9.87873 1.70711ZM12 13C11.4477 13 11 12.5523 11 12L11 7H13L13 12C13 12.5523 12.5523 13 12 13ZM12 14.75C11.3096 14.75 10.75 15.3096 10.75 16C10.75 16.6904 11.3096 17.25 12 17.25C12.6904 17.25 13.25 16.6904 13.25 16C13.25 15.3096 12.6904 14.75 12 14.75Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

DangerDiamondFilledIcon.displayName = "DangerDiamondFilledIcon";
