/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type DenyIconProps = SvgIconNoChildrenProps;

export const DenyIcon = forwardRef<SVGSVGElement, DenyIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M3 12C3 7.02944 7.02944 3 12 3C14.125 3 16.078 3.73647 17.6177 4.9681L4.9681 17.6177C3.73647 16.078 3 14.125 3 12ZM6.38231 19.0319C7.92198 20.2635 9.87499 21 12 21C16.9706 21 21 16.9706 21 12C21 9.87499 20.2635 7.92199 19.0319 6.38231L6.38231 19.0319ZM12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

DenyIcon.displayName = "DenyIcon";
