/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type DevicesIconProps = SvgIconNoChildrenProps;

export const DevicesIcon = forwardRef<SVGSVGElement, DevicesIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5 2C3.34315 2 2 3.34315 2 5V12C2 13.6569 3.34315 15 5 15H9V17H6V19H13V20.5C13 21.3284 13.6716 22 14.5 22H20.5C21.3284 22 22 21.3284 22 20.5V10.5C22 9.67157 21.3284 9 20.5 9H18V5C18 3.34315 16.6569 2 15 2H5ZM16 9V5C16 4.44772 15.5523 4 15 4H5C4.44772 4 4 4.44772 4 5V12C4 12.5523 4.44772 13 5 13H13V10.5C13 9.67157 13.6716 9 14.5 9H16ZM13 15H11V17H13V15ZM15 20V11H20V20H15Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

DevicesIcon.displayName = "DevicesIcon";
