/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type EditIconProps = SvgIconNoChildrenProps;

export const EditIcon = forwardRef<SVGSVGElement, EditIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M16.7071 3.12132C16.3166 2.7308 15.6834 2.7308 15.2929 3.12132L13.9142 4.5L17.5 8.08579L18.8787 6.70711C19.2692 6.31658 19.2692 5.68342 18.8787 5.2929L16.7071 3.12132ZM5 13.4142L12.5 5.91422L16.0858 9.5L8.58579 17H5V13.4142ZM13.8787 1.70711C15.0503 0.535537 16.9497 0.535537 18.1213 1.70711L20.2929 3.87868C21.4645 5.05026 21.4645 6.94975 20.2929 8.12132L9.70711 18.7071L9.41421 19H9H4H3V18V13V12.5858L3.29289 12.2929L13.8787 1.70711ZM3 23H21V21H3V23Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

EditIcon.displayName = "EditIcon";
