/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ExpandLeftIconProps = SvgIconNoChildrenProps;

export const ExpandLeftIcon = forwardRef<SVGSVGElement, ExpandLeftIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 22V2H4V22H2ZM19.5858 13H6V11H19.5858L14.2929 5.70711L15.7071 4.29289L22.1414 10.7272L22.1578 10.7436C22.242 10.8278 22.3427 10.9283 22.424 11.0242C22.5183 11.1352 22.6439 11.3038 22.7195 11.5365C22.8174 11.8377 22.8174 12.1623 22.7195 12.4635C22.6439 12.6962 22.5183 12.8648 22.424 12.9758C22.3427 13.0717 22.2421 13.1722 22.1578 13.2564L22.1578 13.2565L22.1414 13.2728L15.7071 19.7071L14.2929 18.2929L19.5858 13Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ExpandLeftIcon.displayName = "ExpandLeftIcon";
