/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ExternalLinkIconProps = SvgIconNoChildrenProps;

export const ExternalLinkIcon = forwardRef<
  SVGSVGElement,
  ExternalLinkIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M8.29289 14.2929L18.5858 4H10V2H20.2L20.2231 1.99999C20.3423 1.99995 20.4845 1.99989 20.6098 2.01013C20.755 2.02199 20.963 2.05244 21.181 2.16349C21.4632 2.3073 21.6927 2.53677 21.8365 2.81901C21.9476 3.03696 21.978 3.24495 21.9899 3.39017C22.0001 3.51547 22.0001 3.65771 22 3.77682V3.77685V3.77687L22 3.8V14H20V5.41421L9.70711 15.7071L8.29289 14.2929ZM16.0375 20.0339V12.1857L18.0375 10.144V21.0339V22.0339H17.0375H3.02393H2.02393V21.0339V6.96615V5.96615H3.02393H13.8522L11.8106 7.96615H4.02393V20.0339H16.0375Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

ExternalLinkIcon.displayName = "ExternalLinkIcon";
