/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type FilterIconProps = SvgIconNoChildrenProps;

export const FilterIcon = forwardRef<SVGSVGElement, FilterIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M1 4H23V2H1V4ZM4 10H20V8H4V10ZM17 16H7V14H17V16ZM10 22H14V20H10V22Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

FilterIcon.displayName = "FilterIcon";
