/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type HomeIconProps = SvgIconNoChildrenProps;

export const HomeIcon = forwardRef<SVGSVGElement, HomeIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M12 0.654633L12.669 1.2567L22.669 10.2567L23 10.5546V11V20C23 21.6568 21.6569 23 20 23H16H15V22V16C15 14.3431 13.6569 13 12 13C10.3431 13 9 14.3431 9 16V22V23H8H4C2.34315 23 1 21.6568 1 20V11V10.5546L1.33104 10.2567L11.331 1.2567L12 0.654633ZM3 11.4454V20C3 20.5523 3.44772 21 4 21H7V16C7 13.2386 9.23858 11 12 11C14.7614 11 17 13.2386 17 16V21H20C20.5523 21 21 20.5523 21 20V11.4454L12 3.34536L3 11.4454Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

HomeIcon.displayName = "HomeIcon";
