/*!
 * Copyright (c) 2024-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

export * from "./Add";
export * from "./AddCircle";
export * from "./Apps";
export * from "./ArrowBottom";
export * from "./ArrowDown";
export * from "./ArrowLeft";
export * from "./ArrowLowerLeft";
export * from "./ArrowLowerRight";
export * from "./ArrowRight";
export * from "./ArrowTop";
export * from "./ArrowUnsorted";
export * from "./ArrowUp";
export * from "./ArrowUpperLeft";
export * from "./ArrowUpperRight";
export * from "./Aura";
export * from "./Bug";
export * from "./Calendar";
export * from "./Call";
export * from "./Chat";
export * from "./Check";
export * from "./CheckCircleFilled";
export * from "./ChevronDown";
export * from "./ChevronLeft";
export * from "./ChevronRight";
export * from "./ChevronUp";
export * from "./Clock";
export * from "./Close";
export * from "./CloseCircleFilled";
export * from "./CollapseLeft";
export * from "./CollapseRight";
export * from "./Copy";
export * from "./Custom";
export * from "./DangerDiamond";
export * from "./DangerDiamondFilled";
export * from "./Delete";
export * from "./Deny";
export * from "./Devices";
export * from "./Directory";
export * from "./Documentation";
export * from "./Download";
export * from "./DragIndicator";
export * from "./Duo";
export * from "./Edit";
export * from "./Email";
export * from "./ExpandLeft";
export * from "./ExpandRight";
export * from "./ExternalLink";
export * from "./Fido2";
export * from "./Filter";
export * from "./Folder";
export * from "./Globe";
export * from "./GoogleAuth";
export * from "./Grid";
export * from "./Group";
export * from "./Hide";
export * from "./Home";
export * from "./Idp";
export * from "./InformationCircle";
export * from "./InformationCircleFilled";
export * from "./Link";
export * from "./List";
export * from "./Lock";
export * from "./More";
export * from "./Notification";
export * from "./OktaVerify";
export * from "./OnPremMfa";
export * from "./OneTimePassword";
export * from "./Password";
export * from "./Pause";
export * from "./QuestionCircle";
export * from "./QuestionCircleFilled";
export * from "./Refresh";
export * from "./Reset";
export * from "./Resume";
export * from "./Search";
export * from "./SecurityQuestion";
export * from "./Server";
export * from "./Settings";
export * from "./Show";
export * from "./SmartCard";
export * from "./Sms";
export * from "./Subtract";
export * from "./SymantecVip";
export * from "./Sync";
export * from "./ThumbsDown";
export * from "./ThumbsUp";
export * from "./Unlock";
export * from "./Upload";
export * from "./User";
export * from "./Video";
export * from "./VoiceCall";
export * from "./Warning";
export * from "./WarningFilled";
export * from "./Wordmark";
export * from "./Yubikey";
