/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type InformationCircleFilledIconProps = SvgIconNoChildrenProps;

export const InformationCircleFilledIcon = forwardRef<
  SVGSVGElement,
  InformationCircleFilledIconProps
>((props, ref) => {
  return (
    <SvgIcon
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      {...props}
    >
      <>
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12ZM12 8.75C12.6904 8.75 13.25 8.19037 13.25 7.5C13.25 6.80963 12.6904 6.25 12 6.25C11.3096 6.25 10.75 6.80963 10.75 7.5C10.75 8.19037 11.3096 8.75 12 8.75ZM12 10.5C12.5523 10.5 13 10.9477 13 11.5V17.5H11V11.5C11 10.9477 11.4477 10.5 12 10.5Z"
          fill="currentColor"
        />
      </>
    </SvgIcon>
  );
});

InformationCircleFilledIcon.displayName = "InformationCircleFilledIcon";
