/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ListIconProps = SvgIconNoChildrenProps;

export const ListIcon = forwardRef<SVGSVGElement, ListIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5 6C5 7.10457 4.10457 8 3 8C1.89543 8 1 7.10457 1 6C1 4.89543 1.89543 4 3 4C4.10457 4 5 4.89543 5 6ZM3 14C4.10457 14 5 13.1046 5 12C5 10.8954 4.10457 10 3 10C1.89543 10 1 10.8954 1 12C1 13.1046 1.89543 14 3 14ZM3 20C4.10457 20 5 19.1046 5 18C5 16.8954 4.10457 16 3 16C1.89543 16 1 16.8954 1 18C1 19.1046 1.89543 20 3 20ZM8 13H23V11H8V13ZM23 7H8V5H23V7ZM8 19H23V17H8V19Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ListIcon.displayName = "ListIcon";
