/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type LockIconProps = SvgIconNoChildrenProps;

export const LockIcon = forwardRef<SVGSVGElement, LockIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5 11L16 11H17L19 11V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V11ZM7 6L7 9H4H3V10V18C3 20.7614 5.23858 23 8 23H16C18.7614 23 21 20.7614 21 18V10V9H20H17V6C17 3.23858 14.7614 1 12 1C9.23858 1 7 3.23858 7 6ZM15 9V6C15 4.34315 13.6569 3 12 3C10.3431 3 9 4.34315 9 6L9 9L15 9ZM12 17.5C12.8284 17.5 13.5 16.8284 13.5 16C13.5 15.1716 12.8284 14.5 12 14.5C11.1716 14.5 10.5 15.1716 10.5 16C10.5 16.8284 11.1716 17.5 12 17.5Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

LockIcon.displayName = "LockIcon";
