/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ResetIconProps = SvgIconNoChildrenProps;

export const ResetIcon = forwardRef<SVGSVGElement, ResetIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M3 12C3 7.02944 7.02944 3 12 3C15.1192 3 17.8692 4.5867 19.4847 7L16 7V9H21.2L21.2231 9.00001C21.3423 9.00005 21.4845 9.00011 21.6098 8.98987C21.755 8.978 21.963 8.94756 22.181 8.83651C22.4632 8.6927 22.6927 8.46323 22.8365 8.18099C22.9476 7.96304 22.978 7.75505 22.9899 7.60983C23.0001 7.48451 23.0001 7.34226 23 7.22314L23 7.2V2L21 2V5.67414C19.0101 2.84825 15.7216 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12H21C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ResetIcon.displayName = "ResetIcon";
