/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type ServerIconProps = SvgIconNoChildrenProps;

export const ServerIcon = forwardRef<SVGSVGElement, ServerIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M6 1C4.34315 1 3 2.34315 3 4V20C3 21.6569 4.34315 23 6 23H18C19.6569 23 21 21.6569 21 20V4C21 2.34315 19.6569 1 18 1H6ZM5 4C5 3.44772 5.44772 3 6 3H18C18.5523 3 19 3.44772 19 4V7.66667H5V4ZM5 9.66667H19V14.3333H5V9.66667ZM5 16.3333V20C5 20.5523 5.44772 21 6 21H18C18.5523 21 19 20.5523 19 20V16.3333H5ZM8 6.33334C8.55228 6.33334 9 5.88563 9 5.33334C9 4.78106 8.55228 4.33334 8 4.33334C7.44772 4.33334 7 4.78106 7 5.33334C7 5.88563 7.44772 6.33334 8 6.33334ZM8 13C8.55228 13 9 12.5523 9 12C9 11.4477 8.55228 11 8 11C7.44772 11 7 11.4477 7 12C7 12.5523 7.44772 13 8 13ZM9 18.6667C9 19.219 8.55228 19.6667 8 19.6667C7.44772 19.6667 7 19.219 7 18.6667C7 18.1144 7.44772 17.6667 8 17.6667C8.55228 17.6667 9 18.1144 9 18.6667Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

ServerIcon.displayName = "ServerIcon";
