/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type UploadIconProps = SvgIconNoChildrenProps;

export const UploadIcon = forwardRef<SVGSVGElement, UploadIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5.70724 9.70715L11 4.41438L11 18H13L13 4.41414L18.293 9.70715L19.7072 8.29294L13.2729 1.85863L13.2566 1.84228L13.2566 1.84226L13.2565 1.84222C13.1723 1.75797 13.0718 1.65736 12.976 1.576C12.8649 1.4817 12.6963 1.35616 12.4637 1.28057C12.1624 1.18268 11.8379 1.18268 11.5366 1.28057C11.304 1.35616 11.1354 1.4817 11.0243 1.576C10.9285 1.65737 10.8279 1.75799 10.7437 1.84225L10.7437 1.84226L10.7273 1.85863L4.29303 8.29294L5.70724 9.70715ZM4.99994 20V16H2.99994V20C2.99994 21.6569 4.34308 23 5.99994 23H17.9999C19.6568 23 20.9999 21.6569 20.9999 20V16H18.9999V20C18.9999 20.5523 18.5522 21 17.9999 21H5.99994C5.44765 21 4.99994 20.5523 4.99994 20Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

UploadIcon.displayName = "UploadIcon";
