/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type UserIconProps = SvgIconNoChildrenProps;

export const UserIcon = forwardRef<SVGSVGElement, UserIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M15.5 6.5C15.5 8.433 13.933 10 12 10C10.067 10 8.50002 8.433 8.50002 6.5C8.50002 4.567 10.067 3 12 3C13.933 3 15.5 4.567 15.5 6.5ZM17.5 6.5C17.5 9.53757 15.0376 12 12 12C8.96245 12 6.50002 9.53757 6.50002 6.5C6.50002 3.46243 8.96245 1 12 1C15.0376 1 17.5 3.46243 17.5 6.5ZM5 23C5 20.6428 5.69382 18.6374 6.88608 17.2385C8.06424 15.8562 9.78219 15 12 15C14.2152 15 15.9336 15.862 17.1132 17.2493C18.3068 18.6532 19 20.6596 19 23H21C21 20.2779 20.1932 17.7843 18.6369 15.9538C17.0664 14.1067 14.7848 13 12 13C9.21781 13 6.93577 14.0969 5.36393 15.9412C3.80618 17.7689 3 20.2634 3 23H5Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

UserIcon.displayName = "UserIcon";
