/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type VideoIconProps = SvgIconNoChildrenProps;

export const VideoIcon = forwardRef<SVGSVGElement, VideoIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M4 2.99998C2.34315 2.99998 1 4.34313 1 5.99998V18C1 19.6568 2.34315 21 4 21H20C21.6569 21 23 19.6568 23 18V5.99998C23 4.34313 21.6569 2.99998 20 2.99998H4ZM3 5.99998C3 5.4477 3.44772 4.99998 4 4.99998H20C20.5523 4.99998 21 5.4477 21 5.99998V18C21 18.5523 20.5523 19 20 19H4C3.44772 19 3 18.5523 3 18V5.99998ZM16.5528 13.3416C17.6584 12.7888 17.6584 11.2111 16.5528 10.6583L10.1708 7.46735C9.17347 6.96868 8 7.69392 8 8.80899L8 15.191C8 16.306 9.17347 17.0313 10.1708 16.5326L16.5528 13.3416ZM10 9.61801L14.7639 12L10 14.3819V9.61801Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

VideoIcon.displayName = "VideoIcon";
