/*!
 * Copyright (c) 2023-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type WarningIconProps = SvgIconNoChildrenProps;

export const WarningIcon = forwardRef<SVGSVGElement, WarningIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M9.3425 2.91825C10.4655 0.77428 13.5345 0.774279 14.6575 2.91825L22.3521 17.608C23.3984 19.6055 21.9496 22 19.6946 22H4.30538C2.05044 22 0.601579 19.6055 1.64789 17.608L9.3425 2.91825ZM12.8858 3.84627C12.5115 3.13161 11.4885 3.13161 11.1142 3.84627L3.41955 18.536C3.07078 19.2018 3.55374 20 4.30538 20H19.6946C20.4463 20 20.9292 19.2018 20.5804 18.536L12.8858 3.84627ZM12 15.75C11.3096 15.75 10.75 16.3096 10.75 17C10.75 17.6904 11.3096 18.25 12 18.25C12.6903 18.25 13.25 17.6904 13.25 17C13.25 16.3096 12.6903 15.75 12 15.75ZM11 13C11 13.5523 11.4477 14 12 14C12.5523 14 13 13.5523 13 13L13 7.99999L11 7.99999L11 13Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  }
);

WarningIcon.displayName = "WarningIcon";
