/*!
 * Copyright (c) 2024-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import { SvgIcon, type SvgIconNoChildrenProps } from "../SvgIcon";

export type WordmarkIconProps = SvgIconNoChildrenProps;

export const WordmarkIcon = forwardRef<SVGSVGElement, WordmarkIconProps>(
  (props, ref) => {
    return (
      <SvgIcon
        width="56"
        height="21"
        viewBox="0 0 56 21"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        ref={ref}
        {...props}
      >
        <>
          <path
            d="M46.77 17.796c-2.684 0-4.582-2.088-4.582-4.827s1.898-4.826 4.583-4.826c2.684 0 4.528 2.087 4.528 4.826 0 2.74-1.87 4.827-4.528 4.827Zm-.433 2.875c2.17 0 4.013-.841 5.18-2.604.216 1.709 1.463 2.332 3.036 2.332h1.248v-2.712h-.543c-.895 0-1.111-.434-1.111-1.437V5.54h-2.875v2.196c-.976-1.545-2.82-2.467-4.935-2.467-3.77 0-7.24 3.146-7.24 7.7 0 4.556 3.47 7.703 7.24 7.703ZM31.53 16.955c0 2.44 1.518 3.444 3.335 3.444h3.498v-2.712h-2.549c-1.057 0-1.274-.407-1.274-1.437v-8h3.823V5.54H34.54V.549h-3.01v16.406ZM17.837 20.4h3.01v-6.372h1.003l5.125 6.372h3.796l-6.535-8.08 5.017-6.78h-3.39l-4.095 5.722h-.922V.55h-3.01V20.4ZM8.074 5.268C3.871 5.268.4 8.414.4 12.968c0 4.556 3.47 7.702 7.674 7.702 4.203 0 7.674-3.146 7.674-7.701s-3.47-7.701-7.674-7.701Zm0 12.528c-2.685 0-4.583-2.088-4.583-4.827S5.39 8.143 8.074 8.143c2.685 0 4.583 2.087 4.583 4.826 0 2.74-1.898 4.827-4.583 4.827Z"
            fill="currentColor"
          />
        </>
      </SvgIcon>
    );
  },
);

WordmarkIcon.displayName = "WordmarkIcon";
