/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonActionTypes,
  ButtonSizes,
  ButtonTypes,
} from './types';

export namespace Components {
  interface OButton {
    'actionType': ButtonActionTypes;
    'disabled': boolean;
    'href': string;
    'icon': string;
    'size': ButtonSizes;
    'type': ButtonTypes;
  }
}

declare global {


  interface HTMLOButtonElement extends Components.OButton, HTMLStencilElement {}
  var HTMLOButtonElement: {
    prototype: HTMLOButtonElement;
    new (): HTMLOButtonElement;
  };
  interface HTMLElementTagNameMap {
    'o-button': HTMLOButtonElement;
  }
}

declare namespace LocalJSX {
  interface OButton {
    'actionType'?: ButtonActionTypes;
    'disabled'?: boolean;
    'href'?: string;
    'icon'?: string;
    'onOButtonFocus'?: (event: CustomEvent<any>) => void;
    'size'?: ButtonSizes;
    'type'?: ButtonTypes;
  }

  interface IntrinsicElements {
    'o-button': OButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'o-button': LocalJSX.OButton & JSXBase.HTMLAttributes<HTMLOButtonElement>;
    }
  }
}


