/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type AlertCircleIconProps = SvgIconNoChildrenProps;

export const AlertCircleIcon = forwardRef<SVGSVGElement, AlertCircleIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M8 15C11.866 15 15 11.866 15 8C15 4.13401 11.866 1 8 1C4.13401 1 1 4.13401 1 8C1 11.866 4.13401 15 8 15ZM16 8C16 12.4183 12.4183 16 8 16C3.58172 16 0 12.4183 0 8C0 3.58172 3.58172 0 8 0C12.4183 0 16 3.58172 16 8ZM8 12C8.14834 12 8.29334 11.956 8.41668 11.8736C8.54001 11.7912 8.63614 11.6741 8.69291 11.537C8.74968 11.4 8.76453 11.2492 8.73559 11.1037C8.70665 10.9582 8.63522 10.8246 8.53033 10.7197C8.42544 10.6148 8.29181 10.5434 8.14632 10.5144C8.00083 10.4855 7.85003 10.5003 7.71299 10.5571C7.57594 10.6139 7.45881 10.71 7.3764 10.8333C7.29399 10.9567 7.25 11.1017 7.25 11.25C7.25 11.4489 7.32902 11.6397 7.46967 11.7803C7.61032 11.921 7.80109 12 8 12ZM7.5 8.5C7.5 8.77614 7.72386 9 8 9C8.27614 9 8.5 8.77614 8.5 8.5V4H7.5L7.5 8.5Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

AlertCircleIcon.displayName = "AlertCircleIcon";
