/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ArrowDownIconProps = SvgIconNoChildrenProps;

export const ArrowDownIcon = forwardRef<SVGSVGElement, ArrowDownIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M8.50001 13.2929L12.6465 9.14645L13.3536 9.85355L8.35356 14.8536C8.1583 15.0488 7.84172 15.0488 7.64645 14.8536L2.64645 9.85355L3.35356 9.14645L7.50001 13.2929L7.50001 1L8.50001 1L8.50001 13.2929Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

ArrowDownIcon.displayName = "ArrowDownIcon";
