/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ArrowUpIconProps = SvgIconNoChildrenProps;

export const ArrowUpIcon = forwardRef<SVGSVGElement, ArrowUpIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M7.50001 2.70711L3.35356 6.85355L2.64645 6.14645L7.64645 1.14645C7.84172 0.951185 8.1583 0.951185 8.35356 1.14645L13.3536 6.14645L12.6465 6.85355L8.50001 2.70711L8.50001 15L7.50001 15L7.50001 2.70711Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

ArrowUpIcon.displayName = "ArrowUpIcon";
