/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type CalendarIconProps = SvgIconNoChildrenProps;

export const CalendarIcon = forwardRef<SVGSVGElement, CalendarIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5 3V4H6V3H10V4H11V3H14V6H2V3H5ZM5 2H2H1V3V11.8C1 12.9201 1 13.4802 1.21799 13.908C1.40973 14.2843 1.71569 14.5903 2.09202 14.782C2.51984 15 3.0799 15 4.2 15H11.8C12.9201 15 13.4802 15 13.908 14.782C14.2843 14.5903 14.5903 14.2843 14.782 13.908C15 13.4802 15 12.9201 15 11.8V3V2H14H11V0H10V2H6V0H5V2ZM2 11.8V7H14V11.8C14 12.3766 13.9992 12.7488 13.9761 13.0322C13.9539 13.3038 13.9162 13.4045 13.891 13.454C13.7951 13.6422 13.6422 13.7951 13.454 13.891C13.4045 13.9162 13.3038 13.9539 13.0322 13.9761C12.7488 13.9992 12.3766 14 11.8 14H4.2C3.62345 14 3.25117 13.9992 2.96784 13.9761C2.69617 13.9539 2.59545 13.9162 2.54601 13.891C2.35785 13.7951 2.20487 13.6422 2.10899 13.454C2.0838 13.4045 2.04612 13.3038 2.02393 13.0322C2.00078 12.7488 2 12.3766 2 11.8Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

CalendarIcon.displayName = "CalendarIcon";
