/*!
 * Copyright (c) 2021-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import { forwardRef } from "react";
import type { ComponentPropsWithRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";

export interface CaretUpIconProps
  extends Omit<ComponentPropsWithRef<"svg">, "style" | "className"> {
  title?: string;
}

const CaretUpIcon = forwardRef<SVGSVGElement, CaretUpIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M3.72595 9.92794L6.00121 7.51056L7 6.49997L7.99879 7.51056L10.274 9.92794C10.6672 10.3457 11.3272 10.3413 11.7204 9.92354C12.099 9.52126 12.0932 8.87949 11.7024 8.48947L7.34957 4.14532C7.15539 3.95152 6.84461 3.95152 6.65043 4.14532L2.29763 8.48947C1.90683 8.87949 1.90095 9.52126 2.27958 9.92354C2.67278 10.3413 3.33275 10.3457 3.72595 9.92794Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

CaretUpIcon.displayName = "CaretUpIcon";

export { CaretUpIcon };
