/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type ChevronUpIconProps = SvgIconNoChildrenProps;

export const ChevronUpIcon = forwardRef<SVGSVGElement, ChevronUpIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M8 5.70711L3.35355 10.3536L2.64645 9.64645L7.64645 4.64645C7.84171 4.45118 8.15829 4.45118 8.35355 4.64645L13.3536 9.64645L12.6464 10.3536L8 5.70711Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

ChevronUpIcon.displayName = "ChevronUpIcon";
