/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type DeleteIconProps = SvgIconNoChildrenProps;

export const DeleteIcon = forwardRef<SVGSVGElement, DeleteIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M5.38743 2L5.72076 1H10.2792L10.6126 2H5.38743ZM4.33333 2L5 0H11L11.6667 2H14H15V3V5V6H14V12.8C14 13.9201 14 14.4802 13.782 14.908C13.5903 15.2843 13.2843 15.5903 12.908 15.782C12.4802 16 11.9201 16 10.8 16H5.2C4.0799 16 3.51984 16 3.09202 15.782C2.71569 15.5903 2.40973 15.2843 2.21799 14.908C2 14.4802 2 13.9201 2 12.8V6H1V5V3V2H2H4.33333ZM12 3H10.9459H5.05409H4H2V5H3H13H14V3H12ZM3 6H13V12.8C13 13.3766 12.9992 13.7488 12.9761 14.0322C12.9539 14.3038 12.9162 14.4045 12.891 14.454C12.7951 14.6422 12.6422 14.7951 12.454 14.891C12.4045 14.9162 12.3038 14.9539 12.0322 14.9761C11.7488 14.9992 11.3766 15 10.8 15H5.2C4.62345 15 4.25117 14.9992 3.96784 14.9761C3.69617 14.9539 3.59545 14.9162 3.54601 14.891C3.35785 14.7951 3.20487 14.6422 3.10899 14.454C3.0838 14.4045 3.04612 14.3038 3.02393 14.0322C3.00078 13.7488 3 13.3766 3 12.8V6Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

DeleteIcon.displayName = "DeleteIcon";
