/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type GlobeIconProps = SvgIconNoChildrenProps;

export const GlobeIcon = forwardRef<SVGSVGElement, GlobeIconProps>(
  (props, ref) => {
    const omitProps = useOmit(props);
    return (
      <SvgIcon ref={ref} {...omitProps}>
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M4.51068 8.5H1.01758C1.24552 11.7297 3.6644 14.3544 6.79697 14.897C5.44825 13.1001 4.61317 10.8946 4.51068 8.5ZM5.51169 8.5H10.4883C10.3759 10.8991 9.45874 13.087 8 14.8011C6.54126 13.087 5.6241 10.8991 5.51169 8.5ZM10.4883 7.5H5.51169C5.6241 5.10093 6.54126 2.91302 8 1.19892C9.45874 2.91302 10.3759 5.10093 10.4883 7.5ZM11.4893 8.5C11.3868 10.8946 10.5517 13.1001 9.20303 14.897C12.3356 14.3544 14.7545 11.7297 14.9824 8.5H11.4893ZM14.9824 7.5H11.4893C11.3868 5.10539 10.5518 2.89994 9.20303 1.10298C12.3356 1.64557 14.7545 4.27033 14.9824 7.5ZM4.51068 7.5H1.01758C1.24552 4.27033 3.6644 1.64558 6.79697 1.10298C5.44825 2.89994 4.61317 5.10539 4.51068 7.5ZM16 8C16 12.4183 12.4183 16 8 16C3.58172 16 0 12.4183 0 8C0 3.58172 3.58172 0 8 0C12.4183 0 16 3.58172 16 8Z"
            fill="currentColor"
          />
        </svg>
      </SvgIcon>
    );
  }
);

GlobeIcon.displayName = "GlobeIcon";
