/*!
 * Copyright (c) 2021-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

export * from "./IconDictionary";

import { AnchorIcon } from "./Anchor";
export * from "./Anchor";

import { ArrowDownIcon } from "./ArrowDown";
export * from "./ArrowDown";

import { ArrowRightIcon } from "./ArrowRight";
export * from "./ArrowRight";

import { CaretDownIcon } from "./CaretDown";
export * from "./CaretDown";

import { CaretUpIcon } from "./CaretUp";
export * from "./CaretUp";

import { CautionIcon } from "./Caution";
export * from "./Caution";

import { CheckIcon } from "./Check";
export * from "./Check";

import { CloseIcon } from "./Close";
export * from "./Close";

import { CompleteIcon } from "./Complete";
export * from "./Complete";

import { CopyIcon } from "./Copy";
export * from "./Copy";

import { DeleteIcon } from "./Delete";
export * from "./Delete";

import { DownloadIcon } from "./Download";
export * from "./Download";

import { EditIcon } from "./Edit";
export * from "./Edit";

import { ErrorIcon } from "./Error";
export * from "./Error";

import { ExternalIcon } from "./External";
export * from "./External";

import { FilterIcon } from "./Filter";
export * from "./Filter";

import { GetInfoIcon } from "./GetInfo";
export * from "./GetInfo";

import { GoBackwardIcon } from "./GoBackward";
export * from "./GoBackward";

import { GoForwardIcon } from "./GoForward";
export * from "./GoForward";

import { MinusIcon } from "./Minus";
export * from "./Minus";

import { NotificationIcon } from "./Notification";
export * from "./Notification";

import { PlusIcon } from "./Plus";
export * from "./Plus";

import { SearchIcon } from "./Search";
export * from "./Search";

import { SettingsIcon } from "./Settings";
export * from "./Settings";

import { SortAscIcon } from "./SortAsc";
export * from "./SortAsc";

import { SortDescIcon } from "./SortDesc";
export * from "./SortDesc";

import { SortIcon } from "./Sort";
export * from "./Sort";

import { UserIcon } from "./User";
export * from "./User";

export const iconDictionary = {
  anchor: AnchorIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-right": ArrowRightIcon,
  "caret-down": CaretDownIcon,
  "caret-up": CaretUpIcon,
  caution: CautionIcon,
  check: CheckIcon,
  close: CloseIcon,
  complete: CompleteIcon,
  copy: CopyIcon,
  delete: DeleteIcon,
  download: DownloadIcon,
  edit: EditIcon,
  error: ErrorIcon,
  external: ExternalIcon,
  filter: FilterIcon,
  "get-info": GetInfoIcon,
  "go-backward": GoBackwardIcon,
  "go-forward": GoForwardIcon,
  minus: MinusIcon,
  notification: NotificationIcon,
  plus: PlusIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  "sort-asc": SortAscIcon,
  "sort-desc": SortDescIcon,
  sort: SortIcon,
  user: UserIcon,
};
