/*!
 * Copyright (c) 2021-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

export * from "./Icon";
export { default } from "./Icon";

import AnchorIcon from "./Anchor";
import ArrowDownIcon from "./ArrowDown";
import ArrowRightIcon from "./ArrowRight";
import CaretDownIcon from "./CaretDown";
import CaretUpIcon from "./CaretUp";
import CautionIcon from "./Caution";
import CheckIcon from "./Check";
import CloseIcon from "./Close";
import CompleteIcon from "./Complete";
import CopyIcon from "./Copy";
import DeleteIcon from "./Delete";
import DownloadIcon from "./Download";
import EditIcon from "./Edit";
import ErrorIcon from "./Error";
import ExternalIcon from "./External";
import FilterIcon from "./Filter";
import GetInfoIcon from "./GetInfo";
import GoBackwardIcon from "./GoBackward";
import GoForwardIcon from "./GoForward";
import MinusIcon from "./Minus";
import NotificationIcon from "./Notification";
import PlusIcon from "./Plus";
import SearchIcon from "./Search";
import SettingsIcon from "./Settings";
import SortAscIcon from "./SortAsc";
import SortDescIcon from "./SortDesc";
import SortIcon from "./Sort";
import UserIcon from "./User";

export {
  AnchorIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  CaretDownIcon,
  CaretUpIcon,
  CautionIcon,
  CheckIcon,
  CloseIcon,
  CompleteIcon,
  CopyIcon,
  DeleteIcon,
  DownloadIcon,
  EditIcon,
  ErrorIcon,
  ExternalIcon,
  FilterIcon,
  GetInfoIcon,
  GoBackwardIcon,
  GoForwardIcon,
  MinusIcon,
  NotificationIcon,
  PlusIcon,
  SearchIcon,
  SettingsIcon,
  SortAscIcon,
  SortDescIcon,
  SortIcon,
  UserIcon,
};

export const iconDictionary = {
  anchor: AnchorIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-right": ArrowRightIcon,
  "caret-down": CaretDownIcon,
  "caret-up": CaretUpIcon,
  caution: CautionIcon,
  check: CheckIcon,
  close: CloseIcon,
  complete: CompleteIcon,
  copy: CopyIcon,
  delete: DeleteIcon,
  download: DownloadIcon,
  edit: EditIcon,
  error: ErrorIcon,
  external: ExternalIcon,
  filter: FilterIcon,
  "get-info": GetInfoIcon,
  "go-backward": GoBackwardIcon,
  "go-forward": GoForwardIcon,
  minus: MinusIcon,
  notification: NotificationIcon,
  plus: PlusIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  "sort-asc": SortAscIcon,
  "sort-desc": SortDescIcon,
  sort: SortIcon,
  user: UserIcon,
};
