/*!
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Code automatically generated by svgr; DO NOT EDIT.

import React, { forwardRef } from "react";
import { useOmit } from "../../utils";
import { SvgIcon } from "./SvgIcon";
import type { SvgIconNoChildrenProps } from "./types";

export type OverflowVerticalIconProps = SvgIconNoChildrenProps;

export const OverflowVerticalIcon = forwardRef<
  SVGSVGElement,
  OverflowVerticalIconProps
>((props, ref) => {
  const omitProps = useOmit(props);
  return (
    <SvgIcon ref={ref} {...omitProps}>
      <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M8 2C7.80222 2 7.60888 2.05865 7.44443 2.16853C7.27998 2.27841 7.15181 2.43459 7.07612 2.61732C7.00043 2.80004 6.98063 3.00111 7.01922 3.19509C7.0578 3.38907 7.15304 3.56725 7.29289 3.70711C7.43274 3.84696 7.61093 3.9422 7.80491 3.98079C7.99889 4.01937 8.19996 3.99957 8.38268 3.92388C8.56541 3.84819 8.72159 3.72002 8.83147 3.55557C8.94135 3.39112 9 3.19778 9 3C9 2.73478 8.89464 2.48043 8.70711 2.29289C8.51957 2.10536 8.26522 2 8 2ZM8 7C7.80222 7 7.60888 7.05865 7.44443 7.16853C7.27998 7.27841 7.15181 7.43459 7.07612 7.61732C7.00043 7.80004 6.98063 8.00111 7.01922 8.19509C7.0578 8.38907 7.15304 8.56725 7.29289 8.70711C7.43274 8.84696 7.61093 8.9422 7.80491 8.98079C7.99889 9.01937 8.19996 8.99957 8.38268 8.92388C8.56541 8.84819 8.72159 8.72002 8.83147 8.55557C8.94135 8.39112 9 8.19778 9 8C9 7.73478 8.89464 7.48043 8.70711 7.29289C8.51957 7.10536 8.26522 7 8 7ZM7.44443 12.1685C7.60888 12.0586 7.80222 12 8 12C8.26522 12 8.51957 12.1054 8.70711 12.2929C8.89464 12.4804 9 12.7348 9 13C9 13.1978 8.94135 13.3911 8.83147 13.5556C8.72159 13.72 8.56541 13.8482 8.38268 13.9239C8.19996 13.9996 7.99889 14.0194 7.80491 13.9808C7.61093 13.9422 7.43274 13.847 7.29289 13.7071C7.15304 13.5673 7.0578 13.3891 7.01922 13.1951C6.98063 13.0011 7.00043 12.8 7.07612 12.6173C7.15181 12.4346 7.27998 12.2784 7.44443 12.1685Z"
          fill="currentColor"
        />
      </svg>
    </SvgIcon>
  );
});

OverflowVerticalIcon.displayName = "OverflowVerticalIcon";
