import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { Project } from "ts-morph";

import {
  extractComponentDeprecation,
  extractComponentDescription,
  extractComponentInformation,
  extractDeprecatedExports,
  findRepoRoot,
  generatedFileHeader,
  isNonNull,
  mapValues,
} from "./utils.js";

describe(generatedFileHeader.name, () => {
  test("produces the expected header comment with the script name", () => {
    expect(generatedFileHeader("myScript.ts")).toBe(
      "// Code automatically generated by scripts/myScript.ts; DO NOT EDIT.\n\n",
    );
  });
});

describe(isNonNull.name, () => {
  test("returns true for a defined value", () => {
    expect(isNonNull("hello")).toBe(true);
    expect(isNonNull(0)).toBe(true);
    expect(isNonNull(false)).toBe(true);
  });

  test("returns false for null", () => {
    expect(isNonNull(null)).toBe(false);
  });

  test("returns false for undefined", () => {
    expect(isNonNull(undefined)).toBe(false);
  });
});

describe(mapValues.name, () => {
  test("transforms every value with the transform function", () => {
    expect(mapValues({ a: 1, b: 2 }, (value) => value * 2)).toEqual({
      a: 2,
      b: 4,
    });
  });

  test("passes the key as the second argument to the transform", () => {
    expect(
      mapValues({ foo: "bar" }, (value, key) => `${key}:${value}`),
    ).toEqual({ foo: "foo:bar" });
  });

  test("empty record produces empty record", () => {
    expect(mapValues({}, (value) => value)).toEqual({});
  });
});

describe(findRepoRoot.name, () => {
  test("finds the monorepo root by locating lerna.json", () => {
    const root = findRepoRoot(import.meta.dirname);
    expect(existsSync(resolve(root, "lerna.json"))).toBe(true);
  });

  test("throws when no lerna.json is found in the directory tree", () => {
    expect(() => findRepoRoot("/")).toThrow("Could not find repo root");
  });
});

const makeProject = (filePath: string, source: string) => {
  const project = new Project({ useInMemoryFileSystem: true });
  project.createSourceFile(filePath, source);
  return project;
};

describe(extractComponentDescription.name, () => {
  test("returns JSDoc description from a declare const declaration", () => {
    const project = makeProject(
      "/types/Button.d.ts",
      `/** Renders a clickable button element. */\ndeclare const Button: () => null;`,
    );
    expect(
      extractComponentDescription({
        componentName: "Button",
        typeFile: project.getSourceFile("/types/Button.d.ts"),
      }),
    ).toBe("Renders a clickable button element.");
  });

  test("returns empty string when no JSDoc is present", () => {
    const project = makeProject(
      "/types/Link.d.ts",
      `declare const Link: () => null;`,
    );
    expect(
      extractComponentDescription({
        componentName: "Link",
        typeFile: project.getSourceFile("/types/Link.d.ts"),
      }),
    ).toBe("");
  });

  test("falls back to sourceFile when typeFile has no description", () => {
    const project = makeProject(
      "/src/Badge.tsx",
      `/** Displays a numeric count. */\nconst Badge = () => null;`,
    );
    expect(
      extractComponentDescription({
        componentName: "Badge",
        sourceFile: project.getSourceFile("/src/Badge.tsx"),
      }),
    ).toBe("Displays a numeric count.");
  });
});

describe(extractComponentDeprecation.name, () => {
  test("returns the @deprecated message when present", () => {
    const project = makeProject(
      "/types/OldButton.d.ts",
      `/**\n * @deprecated Use Button instead.\n */\ndeclare const OldButton: () => null;`,
    );
    expect(
      extractComponentDeprecation({
        componentName: "OldButton",
        typeFile: project.getSourceFile("/types/OldButton.d.ts"),
      }),
    ).toBe("Use Button instead.");
  });

  test("returns undefined when there is no @deprecated tag", () => {
    const project = makeProject(
      "/types/Button.d.ts",
      `/** A normal component. */\ndeclare const Button: () => null;`,
    );
    expect(
      extractComponentDeprecation({
        componentName: "Button",
        typeFile: project.getSourceFile("/types/Button.d.ts"),
      }),
    ).toBeUndefined();
  });
});

describe(extractDeprecatedExports.name, () => {
  test("returns entries for export declarations with @deprecated leading comment", () => {
    const project = makeProject(
      "/src/index.ts",
      `/** @deprecated Use Button instead. */\nexport { OldButton } from "./OldButton.js";\nexport { TextField } from "./TextField.js";`,
    );
    expect(
      extractDeprecatedExports(project.getSourceFile("/src/index.ts")),
    ).toEqual([{ name: "OldButton", message: "Use Button instead." }]);
  });

  test("returns empty array when no exports are deprecated", () => {
    const project = makeProject(
      "/src/index.ts",
      `export { Button } from "./Button.js";\nexport { Link } from "./Link.js";`,
    );
    expect(
      extractDeprecatedExports(project.getSourceFile("/src/index.ts")),
    ).toEqual([]);
  });

  test("returns empty array for undefined source file", () => {
    expect(extractDeprecatedExports(undefined)).toEqual([]);
  });
});

describe(extractComponentInformation.name, () => {
  test("extracts props with description, type, required, and default value", () => {
    const project = new Project({ useInMemoryFileSystem: true });
    // Description is read from the source file (.tsx), not the types file (.d.ts)
    project.createSourceFile(
      "/src/Button.tsx",
      `/** Renders a button. */\nconst Button = () => null;`,
    );
    project.createSourceFile(
      "/types/Button.d.ts",
      `declare const Button: () => null;

export type ButtonProps = {
  /** The visual variant. @default "primary" */
  variant?: "primary" | "secondary";
  /** The button label. */
  label: string;
};
`,
    );

    const result = extractComponentInformation({
      project,
      typesFilePath: "/types/Button.d.ts",
      sourceFilePath: "/src/Button.tsx",
      componentName: "Button",
    });

    expect(result.description).toBe("Renders a button.");
    expect(result.props).toEqual([
      {
        name: "variant",
        description: "The visual variant.",
        required: false,
        type: { name: '"primary" | "secondary"' },
        defaultValue: { value: '"primary"' },
      },
      {
        name: "label",
        description: "The button label.",
        required: true,
        type: { name: "string" },
        defaultValue: null,
      },
    ]);
  });

  test("extracts @deprecated from a prop", () => {
    const project = makeProject(
      "/types/Foo.d.ts",
      `declare const Foo: () => null;

export type FooProps = {
  /** Old prop. @deprecated Use newProp instead. */
  oldProp?: string;
  newProp?: string;
};
`,
    );
    const result = extractComponentInformation({
      project,
      typesFilePath: "/types/Foo.d.ts",
      componentName: "Foo",
    });

    const oldPropEntry = result.props.find((prop) => prop.name === "oldProp");
    expect(oldPropEntry?.deprecated).toBe("Use newProp instead.");
  });

  test("returns empty props array when no Props type is defined", () => {
    const project = makeProject(
      "/types/NoProps.d.ts",
      `declare const NoProps: () => null;`,
    );
    const result = extractComponentInformation({
      project,
      typesFilePath: "/types/NoProps.d.ts",
      componentName: "NoProps",
    });

    expect(result.props).toEqual([]);
  });
});
