import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type Node,
  Project,
  PropertySignature,
  type SourceFile,
  SyntaxKind,
  type Symbol as TsMorphSymbol,
} from "ts-morph";

import type { PropMetadata } from "../src/metadata-types.js";

export type { ComponentMetadata, PropMetadata } from "../src/metadata-types.js";

export const generatedFileHeader = (scriptName: string) =>
  `// Code automatically generated by scripts/${scriptName}; DO NOT EDIT.\n\n`;

export const findRepoRoot = (current: string): string => {
  if (existsSync(resolve(current, "lerna.json"))) return current;
  const parent = dirname(current);
  if (parent === current)
    throw new Error(`Could not find repo root from ${current}`);
  return findRepoRoot(parent);
};

export const resolveScriptPaths = (
  importMetaUrl: string,
): { repoRoot: string; scriptsDir: string } => {
  const scriptsDir = dirname(fileURLToPath(importMetaUrl));
  return { scriptsDir, repoRoot: findRepoRoot(scriptsDir) };
};

export type WriteGeneratedFileArgs = {
  content: string;
  outputFileName: string;
  scriptName: string;
  scriptsDir: string;
};

export const writeGeneratedFile = async ({
  scriptsDir,
  scriptName,
  outputFileName,
  content,
}: WriteGeneratedFileArgs): Promise<void> => {
  const outputPath = resolve(scriptsDir, "../src", outputFileName);
  await writeFile(outputPath, content);
  console.info(`[${scriptName}] Written to ${outputPath}`);
};

export const isNonNull = <T>(value: T | null | undefined): value is T =>
  value !== null && value !== undefined;

export const mapValues = <Key extends string, Value, Result>(
  record: Record<Key, Value>,
  transform: (value: Value, key: Key) => Result,
): Record<Key, Result> =>
  Object.fromEntries(
    Object.entries(record).map(([key, value]) => [
      key,
      transform(value as Value, key as Key),
    ]),
  ) as Record<Key, Result>;

const hasGetJsDocs = (
  node: Node,
): node is Node & { getJsDocs(): ReturnType<PropertySignature["getJsDocs"]> } =>
  "getJsDocs" in node &&
  typeof (node as Record<string, unknown>)["getJsDocs"] === "function";

type ResolveTypeNameArgs = {
  declaration: Node;
  propSymbol: TsMorphSymbol;
};

// Type text as written in the declaration, not resolved across files or libraries —
// EXCEPT string/number literal unions.
// (e.g. `(typeof buttonVariantValues)[number]` -> `"primary" | "secondary" | "tertiary"`)
const resolveTypeName = ({
  propSymbol,
  declaration,
}: ResolveTypeNameArgs): string => {
  const propType = propSymbol.getTypeAtLocation(declaration);
  if (propType.isUnion()) {
    const definedMembers = propType
      .getUnionTypes()
      .filter((member) => !member.isUndefined());
    const isLiteralUnion =
      definedMembers.length > 0 &&
      definedMembers.every(
        (member) => member.isStringLiteral() || member.isNumberLiteral(),
      );
    if (isLiteralUnion) {
      return definedMembers.map((member) => member.getText()).join(" | ");
    }
  }
  const propertySignature = declaration.asKind(SyntaxKind.PropertySignature);
  return propertySignature
    ? (propertySignature.getTypeNode()?.getText() ?? "unknown")
    : propType.getText();
};

const extractPropDescription = (declaration: Node): string | undefined =>
  hasGetJsDocs(declaration)
    ? declaration.getJsDocs().at(-1)?.getDescription().trim()
    : undefined;

const extractPropDefaultValue = (
  declaration: Node,
): { value: unknown } | null => {
  if (!hasGetJsDocs(declaration)) return null;
  const commentText = declaration
    .getJsDocs()
    .at(-1)
    ?.getTags()
    .find((jsDocTag) => jsDocTag.getTagName() === "default")
    ?.getCommentText();
  return commentText !== undefined ? { value: commentText } : null;
};

const extractPropDeprecation = (declaration: Node): string | undefined => {
  if (!hasGetJsDocs(declaration)) return undefined;
  const commentText = declaration
    .getJsDocs()
    .flatMap((jsDoc) => jsDoc.getTags())
    .find((jsDocTag) => jsDocTag.getTagName() === "deprecated")
    ?.getCommentText();
  return commentText?.trim() || undefined;
};

const isFromLocalPackage = (propSymbol: TsMorphSymbol): boolean => {
  const declaration = propSymbol.getDeclarations()[0];
  return (
    declaration !== undefined &&
    !declaration.getSourceFile().getFilePath().includes("node_modules")
  );
};

const toPropMetadataEntry = (propSymbol: TsMorphSymbol): PropMetadata => {
  const declaration = propSymbol.getDeclarations()[0];
  if (!declaration) {
    throw new Error(`No declaration found for prop ${propSymbol.getName()}`);
  }
  const deprecated = extractPropDeprecation(declaration);
  return {
    name: propSymbol.getName(),
    description: extractPropDescription(declaration) ?? "",
    required: !propSymbol.isOptional(),
    type: { name: resolveTypeName({ propSymbol, declaration }) },
    defaultValue: extractPropDefaultValue(declaration),
    ...(deprecated !== undefined && { deprecated }),
  };
};

type GetComponentDescriptionArgs = {
  componentName: string;
  file?: SourceFile;
};

const getComponentJsDoc = ({
  file,
  componentName,
}: GetComponentDescriptionArgs) =>
  file
    ?.getVariableDeclaration(componentName)
    ?.getFirstAncestorByKind(SyntaxKind.VariableStatement)
    ?.getJsDocs()
    .at(-1);

const getComponentDescription = (args: GetComponentDescriptionArgs) =>
  getComponentJsDoc(args)?.getDescription().trim();

const getComponentDeprecation = (args: GetComponentDescriptionArgs) =>
  getComponentJsDoc(args)
    ?.getTags()
    .find((tag) => tag.getTagName() === "deprecated")
    ?.getCommentText()
    ?.trim();

type ExtractComponentDescriptionArgs = {
  componentName: string;
  sourceFile?: SourceFile;
  typeFile?: SourceFile;
};

// Reads the JSDoc description from the component's `declare const Foo` export.
// Returns "" when missing.
export const extractComponentDescription = ({
  componentName,
  sourceFile,
  typeFile,
}: ExtractComponentDescriptionArgs): string => {
  return (
    getComponentDescription({ file: typeFile, componentName }) ??
    getComponentDescription({ file: sourceFile, componentName }) ??
    ""
  );
};

export const extractComponentDeprecation = ({
  componentName,
  sourceFile,
  typeFile,
}: ExtractComponentDescriptionArgs): string | undefined => {
  return (
    getComponentDeprecation({ file: typeFile, componentName }) ??
    getComponentDeprecation({ file: sourceFile, componentName })
  );
};

export type DeprecatedExport = {
  message: string;
  name: string;
};

// A regex on the full source can't reliably associate a comment with its export — it
// breaks on aliases, namespace exports, and missing trailing commas. The AST locates
// the correct node first; then we regex only its leading comment text.
const extractLeadingDeprecation = (node: Node): string | undefined => {
  const sourceText = node.getSourceFile().getFullText();
  const leadingText = sourceText.slice(node.getFullStart(), node.getStart());
  const match = leadingText.match(/\/\*\*\s*@deprecated\s+([\s\S]*?)\s*\*\//);
  return match ? match[1].trim() : undefined;
};

export const extractDeprecatedExports = (
  sourceFile: SourceFile | undefined,
): DeprecatedExport[] => {
  if (!sourceFile) return [];
  return sourceFile.getExportDeclarations().flatMap((exportDeclaration) => {
    const declarationMessage = extractLeadingDeprecation(exportDeclaration);

    if (exportDeclaration.isNamespaceExport()) {
      if (declarationMessage === undefined) return [];
      return Array.from(
        exportDeclaration
          .getModuleSpecifierSourceFile()
          ?.getExportedDeclarations()
          .keys() ?? [],
      )
        .filter((name) => name !== "default")
        .map((name) => ({ name, message: declarationMessage }));
    }

    return exportDeclaration.getNamedExports().flatMap((specifier) => {
      const message =
        declarationMessage ?? extractLeadingDeprecation(specifier);
      if (message === undefined) return [];
      return [{ name: specifier.getName(), message }];
    });
  });
};

type ExtractComponentInformationArgs = {
  componentName: string;
  project: Project;
  sourceFilePath?: string;
  typesFilePath: string;
};

export const extractComponentInformation = ({
  project,
  typesFilePath,
  sourceFilePath,
  componentName,
}: ExtractComponentInformationArgs) => {
  const typeFile = project.addSourceFileAtPathIfExists(typesFilePath);
  const sourceFile = sourceFilePath
    ? project.addSourceFileAtPathIfExists(sourceFilePath)
    : undefined;

  const propsTypeDefinition =
    typeFile?.getTypeAlias(`${componentName}Props`) ??
    typeFile?.getInterface(`${componentName}Props`);

  const description = extractComponentDescription({
    sourceFile,
    componentName,
  });

  const deprecated = extractComponentDeprecation({ sourceFile, componentName });

  return {
    description,
    ...(deprecated !== undefined && { deprecated }),
    props:
      propsTypeDefinition
        ?.getType()
        .getProperties()
        .filter(isFromLocalPackage)
        .map(toPropMetadataEntry) ?? [],
  };
};
